-- pgTAP: Playbook round trip (Section 2.1, Section 18 gate 14). Generated by @xos/canon-import; do not edit.
-- Each sheet exported from the database through xpms.v_playbook_<sheet> must hash to the source checksum,
-- with only the cells and rows in canon/map/ruling-differences.yaml changed by owner rulings.
begin;
create extension if not exists pgtap with schema extensions;
set search_path = extensions, public;

select plan(46);

select is(xpms.playbook_checksum('Cover Page'), 'd9c47c27bf519e556e92a3ffdb4c929feb14b35a970582d305176a8b9654726d', 'Cover Page round-trips');
select is(xpms.playbook_checksum('Projects'), '4d9b66d51246e9a59da9f7d7d088d82aed650da9148a7b99e83bfa34b7c1b8d9', 'Projects round-trips');
select is(xpms.playbook_checksum('Activity Log'), '77ffbaa06456ca1f7c6b0de7b65ecb7cf1d1082ac8740716d9beb7e48f870d69', 'Activity Log round-trips');
select is(xpms.playbook_checksum('Production Schedule'), '3e7a8de6c4540420160d2428e433b8abe01064e75c8cb146f6c840fb47ca2b80', 'Production Schedule round-trips');
select is(xpms.playbook_checksum('Production Tasks'), '0d5773b1a662ef0f7ebad36c4dab95941eacbf4c5429718316aac6bfb0d8b22e', 'Production Tasks round-trips');
select is(xpms.playbook_checksum('Work Orders'), '06c9fb0443377c08b995ca53dd13cfb96c3dbd35f69fc30f58b335eace1bc4a2', 'Work Orders round-trips');
select is(xpms.playbook_checksum('Run of Show'), '19513c8948bfc18ca2326d62dcabd3aaf1606fe7e83c2ff328a16d3e7bc81956', 'Run of Show round-trips');
select is(xpms.playbook_checksum('SOP Library'), '9157198f2364273e0199e34ca1cf72a20853351d0482c0d2faada29170cc6ea3', 'SOP Library round-trips');
select is(xpms.playbook_checksum('Locations'), 'd4b156721a65c55aaab1bd7952e357f6197706c80314624a992665f2ffc6eba2', 'Locations round-trips');
select is(xpms.playbook_checksum('Shipping Manifest'), 'e1b978f050db0570938bc27061683eaaa399181ce6255526ca092d506a386cb5', 'Shipping Manifest round-trips');
select is(xpms.playbook_checksum('Marshalling Yard Log'), 'c26ab66d891d4ebb9cf5dd2f90cecbe133e4e307f7478a3a8c2b5977effc222e', 'Marshalling Yard Log round-trips');
select is(xpms.playbook_checksum('Advance Requests'), '5d37a8702f7d66111c2f488011f382695e9e56d8cbfa9d98ce67d162d67e1407', 'Advance Requests round-trips');
select is(xpms.playbook_checksum('Hospitality Fulfillment'), 'b2af0112795e3a84816d4d90b79606a3eeadc2844bab67573266d8d3a0d269d2', 'Hospitality Fulfillment round-trips');
select is(xpms.playbook_checksum('Asset Inventory'), 'b5ebf584c54d4fdf8fd35493f18a9d9b9dbf143dcd16dd9609f2e79e8f806e1b', 'Asset Inventory round-trips');
select is(xpms.playbook_checksum('Asset Assignments'), 'e1c0fc84dbe9c9327c522b0e6dba20bebd34808b5ba4e8dfcc155b6e6b189aef', 'Asset Assignments round-trips');
select is(xpms.playbook_checksum('Personnel Roster'), '3f4d60a43cc94a495ba2d203e347896cff718b03b7b3a49d4d89a66fca8829dd', 'Personnel Roster round-trips');
select is(xpms.playbook_checksum('Staffing Requisition'), '5e0a6164fcaeb9d991731a4a755a6d996b6464ef885f63659b39bae9d745e78e', 'Staffing Requisition round-trips');
select is(xpms.playbook_checksum('Crew Shifts'), '2e21e4409501d1a07e396dc0199ff329700d107071dde35b6672fd4361caf5d3', 'Crew Shifts round-trips');
select is(xpms.playbook_checksum('Crew Timesheets'), '00730addb950f652e5c8169c40b7af2e12b3e9b9b31f35007307ea11fe7aa768', 'Crew Timesheets round-trips');
select is(xpms.playbook_checksum('Labor Rate Cards'), 'bcbbdf05788e578a819ceb4705e40e98e2046a83d09c0ea4d11b31ceb42c9eb7', 'Labor Rate Cards round-trips');
select is(xpms.playbook_checksum('Roles Library'), 'df23f91eb4ac32997a01fc622305f073ee6623b903b4f757e4360ff8fe7df665', 'Roles Library round-trips');
select is(xpms.playbook_checksum('Credential Issuance'), '8cdf45ed132bfd8ec08977c0a586e44cc6ec433674f477a47fe8545ef0cb3cd5', 'Credential Issuance round-trips');
select is(xpms.playbook_checksum('Access Grid'), '3b494173a011af762fec8f33b87d527a66c770b9da11990b01fc7237d8824944', 'Access Grid round-trips');
select is(xpms.playbook_checksum('Budget Expenses'), '8f1f46e91f99648d0801fad8ae74a5a288effb25d96c79fbd137d735ba7bb0e1', 'Budget Expenses round-trips');
select is(xpms.playbook_checksum('Change Orders'), '41b32aed15b3a3ed8e9b8edae505279b735fe1d9faa30f70f651fba5dfcea42d', 'Change Orders round-trips');
select is(xpms.playbook_checksum('Purchase Orders'), '31ac09fb9a2a3dc95cdac7c1f93e07256d126cf4e9359ff9e4ab1708a1ff4aff', 'Purchase Orders round-trips');
select is(xpms.playbook_checksum('PO Line Items'), '96ee829f2cdc6f2e755ac65d41ace03b9a05335b128ff2e6d82456b4591a9120', 'PO Line Items round-trips');
select is(xpms.playbook_checksum('Universal Posting Line'), 'b116101b580f4200e1c09a600ec35b93659f2760b44d5ab22af8de9d91875052', 'Universal Posting Line round-trips');
select is(xpms.playbook_checksum('Procurement Catalog'), '3fc289092bd8d4ee326c7868f8224d15eaeb9da30599e203a33416ec07346d3c', 'Procurement Catalog round-trips');
select is(xpms.playbook_checksum('Vendor Directory'), 'b4ab949561a91aefb3fce4679d0fdba5584d60c2d06bcd7ee000aac23985d6a3', 'Vendor Directory round-trips');
select is(xpms.playbook_checksum('Vendor Classes'), 'f9b8f434384b1511ac4c044254bd97582536617515afc9f4b94abd36a80fdeca', 'Vendor Classes round-trips');
select is(xpms.playbook_checksum('Vendor Entitlements'), '84f178a70da1efb02e502e19112d4bc53c0afbba4cbf6a0e11eba6d867caba2b', 'Vendor Entitlements round-trips');
select is(xpms.playbook_checksum('Inspection Compliance'), '76cfaf43397f18ec55785a04936c69cb8ad6f93c36b427a3cdc36488cbab325b', 'Inspection Compliance round-trips');
select is(xpms.playbook_checksum('Incident CAD Log'), 'b2beacbabf457e99ba538b9c674624299eb8a786f0346763716f86378aedbadd', 'Incident CAD Log round-trips');
select is(xpms.playbook_checksum('Emergency Codes'), '2a19ec8b06f721f0ac9499046bf9bc4638d4900055bc168b5cbf0e1af01253ce', 'Emergency Codes round-trips');
select is(xpms.playbook_checksum('Radio Channels'), '10cf1e767eaa92da82b38aca85b59cf04f47cd05adab91a321e4db44c103a862', 'Radio Channels round-trips');
select is(xpms.playbook_checksum('Document & Asset Library'), '2d662b5bd44e54052c5064267343214d06a76ba691a56f8916ca0f100c83e1f7', 'Document & Asset Library round-trips');
select is(xpms.playbook_checksum('GL Accounts'), '8406ab6c4150a80cc20b0565f32dde2964254fa8025b649ce9270fc6602ff725', 'GL Accounts round-trips');
select is(xpms.playbook_checksum('Cost Centers'), '18705fb09bfc480a9c0d935c7277a3165e5d1ec690a6a0d6cf19e26980b44b53', 'Cost Centers round-trips');
select is(xpms.playbook_checksum('Departments'), '71ad772af145d588d335dbfa2a3db79b35d190115eac75ee675314cd9f541052', 'Departments round-trips');
select is(xpms.playbook_checksum('Disciplines'), '879a4bd788737860a43e7b320c2d23b519c87134ca7cb3b7ba4e5fcc09d3d6f9', 'Disciplines round-trips');
select is(xpms.playbook_checksum('Categories & URID Master'), '77ad159c5f5130762034bebc77a5209b2eb7102349b0dbf3ec35b0948fd8c3eb', 'Categories & URID Master round-trips');
select is(xpms.playbook_checksum('Teams'), '07d284bff8c1ea2ca573c3baf5981ddbcbbfc639ef37fcd7009fc7d1b858987d', 'Teams round-trips');
select is(xpms.playbook_checksum('Counterparty Types'), '52741acaed98c6e00af1dd230b458fa05d92724cbb82dd475e6ac64473a4eaf8', 'Counterparty Types round-trips');
select is(xpms.playbook_checksum('Verbiage Library'), '332e9f0e484cdccb0f1746422445a484158cb4ada80774210b9c1e82795d5dd2', 'Verbiage Library round-trips');
select is(xpms.playbook_checksum('Enumerations'), '3c52ce09f6e88a302696b1c1fca71b49830374a80ff80b0ccdadb73ab29bef6d', 'Enumerations round-trips');

select * from finish();
rollback;
