-- XOS canon seed (agent A01, migration 0101), extracted from the Bible and the Playbook. The Wave 1 canon import regenerates it from the canon files and must reproduce it exactly.
-- Load after 0100_xpms_canon.sql. Every table here is global canon or Standard Library.
SET search_path = xpms;

INSERT INTO department (class_code, name) VALUES
  ('0000', 'Executive'),
  ('1000', 'Creative'),
  ('2000', 'Talent'),
  ('3000', 'Marketing'),
  ('4000', 'Environment'),
  ('5000', 'Production'),
  ('6000', 'Operations'),
  ('7000', 'Experience'),
  ('8000', 'Hospitality'),
  ('9000', 'Technology');

INSERT INTO gl_account (code, name, type, class_code) VALUES
  ('1000', 'Cash and Bank', 'Asset', NULL),
  ('1100', 'Accounts Receivable', 'Asset', NULL),
  ('1200', 'Prepaid Expenses and Deposits', 'Asset', NULL),
  ('1500', 'Fixed Assets', 'Asset', NULL),
  ('2000', 'Accounts Payable', 'Liability', NULL),
  ('2100', 'Accrued Liabilities', 'Liability', NULL),
  ('2200', 'Deferred Revenue', 'Liability', NULL),
  ('2300', 'Sales Tax Payable', 'Liability', NULL),
  ('3000', 'Equity', 'Equity', NULL),
  ('4000', 'Revenue · Executive', 'Revenue', '0000'),
  ('4300', 'Revenue · Marketing', 'Revenue', '3000'),
  ('4700', 'Revenue · Experience', 'Revenue', '7000'),
  ('4800', 'Revenue · Hospitality', 'Revenue', '8000'),
  ('5000', 'Expense · Executive', 'Expense', '0000'),
  ('5100', 'Expense · Creative', 'Expense', '1000'),
  ('5200', 'Expense · Talent', 'Expense', '2000'),
  ('5300', 'Expense · Marketing', 'Expense', '3000'),
  ('5400', 'Expense · Environment', 'Expense', '4000'),
  ('5500', 'Expense · Production', 'Expense', '5000'),
  ('5600', 'Expense · Operations', 'Expense', '6000'),
  ('5700', 'Expense · Experience', 'Expense', '7000'),
  ('5800', 'Expense · Hospitality', 'Expense', '8000'),
  ('5900', 'Expense · Technology', 'Expense', '9000');

INSERT INTO grade (code, label, sort_order) VALUES
  ('base', 'Base', 1),
  ('elevated', 'Elevated', 2),
  ('premium', 'Premium', 3);

INSERT INTO role_discipline (name) VALUES
  ('Audio Systems'),
  ('Base Build Delivery'),
  ('Beverage Service'),
  ('Building Systems Maintenance'),
  ('Catering Service'),
  ('Commercial and Finance'),
  ('Content Capture'),
  ('Event Security'),
  ('Front of House'),
  ('Governance & Client Relations'),
  ('Guest Safety'),
  ('House Management'),
  ('Lighting Systems'),
  ('Power & Utilities'),
  ('Production Leadership'),
  ('Production Supply'),
  ('Programming & Creative Direction'),
  ('Safety & Security'),
  ('Scenic and Graphics Production'),
  ('Stage Crew'),
  ('Stage Operations'),
  ('Talent Operations'),
  ('Venue IT'),
  ('Venue Services'),
  ('Video Systems');

INSERT INTO role_rank (label) VALUES
  ('Coordinator'),
  ('Crew Chief'),
  ('Director'),
  ('Executive'),
  ('Lead'),
  ('Lead Technician'),
  ('Manager'),
  ('Specialist'),
  ('Supervisor'),
  ('Technician');

INSERT INTO role (role_code, job_title, discipline, rank) VALUES
  ('0000.50.01', 'Chief Executive Officer', 'Governance & Client Relations', 'Executive'),
  ('0000.51.01', 'Production Finance Director', 'Commercial and Finance', 'Director'),
  ('1000.50.01', 'Creative Director', 'Programming & Creative Direction', 'Director'),
  ('1000.50.02', 'Event & Programming Director', 'Programming & Creative Direction', 'Director'),
  ('1000.51.01', 'Scenic Art Director', 'Scenic and Graphics Production', 'Lead'),
  ('2000.50.01', 'Backline Tech / Instrument Specialist', 'Talent Operations', 'Technician'),
  ('2000.50.02', 'Artist Relations Coordinator', 'Talent Operations', 'Coordinator'),
  ('3000.50.01', 'Principal Event Photographer', 'Content Capture', 'Specialist'),
  ('3000.50.02', 'Lead Cinematographer / Video Shooter', 'Content Capture', 'Specialist'),
  ('3000.50.03', 'Real-Time Social Content Producer', 'Content Capture', 'Coordinator'),
  ('4000.50.01', 'Structural Carpenter / Build Lead', 'Base Build Delivery', 'Lead Technician'),
  ('4000.51.01', 'HVAC & Site Climate Tech', 'Building Systems Maintenance', 'Technician'),
  ('5000.50.01', 'Production & Operations Director', 'Production Leadership', 'Director'),
  ('5000.50.02', 'Master Electrician / Power Lead', 'Power & Utilities', 'Lead Technician'),
  ('5000.50.03', 'Production Coordinator', 'Production Leadership', 'Coordinator'),
  ('5000.51.01', 'Lead Stagehand / Deck Crew Chief', 'Stage Crew', 'Crew Chief'),
  ('5000.51.02', 'Head Arena / Festival Rigger', 'Stage Crew', 'Lead Technician'),
  ('5000.51.03', 'Lead System Rigger', 'Stage Crew', 'Technician'),
  ('5000.52.01', 'Special Effects / Pyro Lead', 'Production Supply', 'Lead Technician'),
  ('6000.50.01', 'House Manager', 'House Management', 'Manager'),
  ('6000.50.02', 'Site Safety & Security Lead', 'Safety & Security', 'Lead'),
  ('6000.50.03', 'VIP Experience Manager', 'House Management', 'Manager'),
  ('6000.51.01', 'Janitorial & Waste Operations Lead', 'Venue Services', 'Lead'),
  ('6000.51.02', 'Marshalling Yard & Dock Master', 'Venue Services', 'Manager'),
  ('6000.52.01', 'Security Supervisor', 'Event Security', 'Supervisor'),
  ('7000.50.01', 'Front of House Lead / Box Office Manager', 'Front of House', 'Manager'),
  ('7000.50.02', 'Credential Operations Coordinator', 'Front of House', 'Coordinator'),
  ('7000.51.01', 'Lead Event Paramedic / EMT', 'Guest Safety', 'Specialist'),
  ('8000.50.01', 'Head Beverage Director / Bar Manager', 'Beverage Service', 'Manager'),
  ('8000.51.01', 'Executive Catering Captain', 'Catering Service', 'Manager'),
  ('9000.50.01', 'Production Stage Manager', 'Stage Operations', 'Manager'),
  ('9000.50.02', 'Audio Engineer - A1/FOH', 'Audio Systems', 'Lead Technician'),
  ('9000.50.03', 'Lighting Designer / LD', 'Lighting Systems', 'Lead Technician'),
  ('9000.50.04', 'Video Director / V1', 'Video Systems', 'Lead Technician'),
  ('9000.52.01', 'Lead Network & Comms Engineer', 'Venue IT', 'Lead Technician');

INSERT INTO overtime_rule (rule_id, name, ot_multiplier, dt_multiplier) VALUES
  ('OTR-001', 'Standard Overtime', 1.5, 2),
  ('OTR-002', 'Exempt', 1, 1);

INSERT INTO jurisdiction (jurisdiction_id, level, parent, unit_system, currency, status, note) VALUES
  ('US', 'country', NULL, 'imperial', 'USD', 'populated', 'All 2.x code-derived rules were authored against US model codes.'),
  ('US-FL', 'region', 'US', NULL, NULL, 'populated', 'Florida amendments to the model codes.'),
  ('US-FL-MIAMI-DADE', 'ahj', 'US-FL', NULL, NULL, 'populated', 'The 22-rule permit engine authored in XMCE V2 binds here.'),
  ('GB', 'country', NULL, 'metric', 'GBP', 'declared-unpopulated', 'Declared for the London office. No rules. Resolution refuses.'),
  ('MX', 'country', NULL, 'metric', 'MXN', 'declared-unpopulated', 'No rules. Resolution refuses.'),
  ('AE', 'country', NULL, 'metric', 'AED', 'declared-unpopulated', 'No rules. Resolution refuses.'),
  ('SA', 'country', NULL, 'metric', 'SAR', 'declared-unpopulated', 'No rules. Resolution refuses.');

INSERT INTO jurisdiction_code_set (jurisdiction_id, code_set, sort_order) VALUES
  ('US', 'IBC', 1),
  ('US', 'IPC', 2),
  ('US', 'NFPA', 3),
  ('US', 'ADA', 4),
  ('US-FL', 'FBC', 1),
  ('US-FL', 'Florida Fire Prevention Code', 2),
  ('US-FL-MIAMI-DADE', 'FBC', 1),
  ('US-FL-MIAMI-DADE', 'Miami-Dade County', 2),
  ('GB', 'Approved Documents', 1),
  ('GB', 'BS EN', 2),
  ('MX', 'NOM', 1),
  ('MX', 'Reglamento de Construcciones', 2),
  ('AE', 'UAE Fire and Life Safety Code', 1),
  ('SA', 'Saudi Building Code', 1);

INSERT INTO worker_classification (code, label, is_employee, payment_channel, sort_order) VALUES
  ('EMPLOYEE', 'Employee', true, 'Payroll', 1),
  ('INDEPENDENT_CONTRACTOR', 'Independent Contractor', false, 'Accounts Payable', 2),
  ('VENDOR_SUPPLIED', 'Vendor-Supplied', false, 'Accounts Payable', 3),
  ('UNPAID_INTERN', 'Unpaid Intern', false, 'None', 4),
  ('VOLUNTEER', 'Volunteer', false, 'None', 5);

INSERT INTO classification_document (worker_classification, country, document, purpose) VALUES
  ('EMPLOYEE', 'US', 'Form I-9', 'Onboarding'),
  ('EMPLOYEE', 'US', 'Form W-2', 'Year-End'),
  ('EMPLOYEE', 'US', 'Form W-4', 'Onboarding'),
  ('INDEPENDENT_CONTRACTOR', 'US', 'Form 1099-NEC', 'Year-End'),
  ('INDEPENDENT_CONTRACTOR', 'US', 'Form W-9', 'Onboarding'),
  ('VENDOR_SUPPLIED', 'US', 'Form W-9', 'Onboarding');

INSERT INTO pay_basis (label) VALUES
  ('Day Rate'),
  ('Flat Fee'),
  ('Hourly'),
  ('Salary');

INSERT INTO arrangement (label) VALUES
  ('Per Engagement'),
  ('Retainer');

INSERT INTO pay_basis_classification (pay_basis, worker_classification) VALUES
  ('Day Rate', 'EMPLOYEE'),
  ('Day Rate', 'INDEPENDENT_CONTRACTOR'),
  ('Day Rate', 'VENDOR_SUPPLIED'),
  ('Flat Fee', 'INDEPENDENT_CONTRACTOR'),
  ('Flat Fee', 'VENDOR_SUPPLIED'),
  ('Hourly', 'EMPLOYEE'),
  ('Hourly', 'INDEPENDENT_CONTRACTOR'),
  ('Hourly', 'VENDOR_SUPPLIED'),
  ('Salary', 'EMPLOYEE');

INSERT INTO arrangement_classification (arrangement, worker_classification) VALUES
  ('Per Engagement', 'EMPLOYEE'),
  ('Per Engagement', 'INDEPENDENT_CONTRACTOR'),
  ('Per Engagement', 'VENDOR_SUPPLIED'),
  ('Retainer', 'INDEPENDENT_CONTRACTOR');

INSERT INTO rate_card (rate_card_id, role_code, worker_classification, pay_basis, arrangement, standard_rate, min_grade_rate, max_grade_rate, per_diem_rate, overtime_rule_id) VALUES
  ('LRC-001', '0000.50.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Retainer', 1800, 1500, 2200, 75, 'OTR-002'),
  ('LRC-002', '1000.50.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 1250, 1000, 1500, 75, 'OTR-001'),
  ('LRC-003', '1000.50.02', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 1100, 900, 1350, 75, 'OTR-001'),
  ('LRC-004', '5000.50.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Retainer', 1350, 1100, 1600, 75, 'OTR-001'),
  ('LRC-005', '5000.50.02', 'EMPLOYEE', 'Day Rate', 'Per Engagement', 850, 700, 1000, 75, 'OTR-001'),
  ('LRC-006', '6000.50.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 750, 600, 900, 75, 'OTR-001'),
  ('LRC-007', '6000.50.02', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 700, 550, 850, 75, 'OTR-001'),
  ('LRC-008', '9000.50.01', 'EMPLOYEE', 'Day Rate', 'Per Engagement', 950, 800, 1150, 75, 'OTR-001'),
  ('LRC-009', '9000.50.02', 'VENDOR_SUPPLIED', 'Day Rate', 'Per Engagement', 850, 700, 1000, 75, 'OTR-001'),
  ('LRC-010', '9000.50.03', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 800, 650, 950, 75, 'OTR-001'),
  ('LRC-011', '9000.50.04', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 800, 650, 950, 75, 'OTR-001'),
  ('LRC-012', '0000.51.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 1200, 1000, 1450, 75, 'OTR-002'),
  ('LRC-013', '1000.51.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 900, 750, 1100, 75, 'OTR-001'),
  ('LRC-014', '2000.50.01', 'EMPLOYEE', 'Day Rate', 'Per Engagement', 650, 550, 800, 75, 'OTR-001'),
  ('LRC-015', '2000.50.02', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 550, 450, 700, 75, 'OTR-001'),
  ('LRC-016', '3000.50.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 800, 650, 1000, 75, 'OTR-001'),
  ('LRC-017', '3000.50.02', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 900, 750, 1150, 75, 'OTR-001'),
  ('LRC-018', '3000.50.03', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 600, 500, 750, 75, 'OTR-001'),
  ('LRC-019', '4000.50.01', 'EMPLOYEE', 'Day Rate', 'Per Engagement', 700, 600, 850, 75, 'OTR-001'),
  ('LRC-020', '4000.51.01', 'VENDOR_SUPPLIED', 'Day Rate', 'Per Engagement', 650, 550, 800, 75, 'OTR-001'),
  ('LRC-021', '5000.50.03', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 600, 500, 750, 75, 'OTR-001'),
  ('LRC-022', '5000.51.01', 'EMPLOYEE', 'Day Rate', 'Per Engagement', 550, 450, 700, 75, 'OTR-001'),
  ('LRC-023', '5000.51.02', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 950, 800, 1150, 75, 'OTR-001'),
  ('LRC-024', '5000.51.03', 'EMPLOYEE', 'Day Rate', 'Per Engagement', 750, 650, 900, 75, 'OTR-001'),
  ('LRC-025', '5000.52.01', 'VENDOR_SUPPLIED', 'Day Rate', 'Per Engagement', 800, 650, 1000, 75, 'OTR-001'),
  ('LRC-026', '6000.50.03', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 700, 550, 850, 75, 'OTR-001'),
  ('LRC-027', '6000.51.01', 'EMPLOYEE', 'Day Rate', 'Per Engagement', 450, 380, 550, 50, 'OTR-001'),
  ('LRC-028', '6000.51.02', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 700, 600, 850, 75, 'OTR-001'),
  ('LRC-029', '6000.52.01', 'VENDOR_SUPPLIED', 'Day Rate', 'Per Engagement', 600, 500, 750, 75, 'OTR-001'),
  ('LRC-030', '7000.50.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 650, 500, 800, 75, 'OTR-001'),
  ('LRC-031', '7000.50.02', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 550, 450, 700, 75, 'OTR-001'),
  ('LRC-032', '7000.51.01', 'VENDOR_SUPPLIED', 'Day Rate', 'Per Engagement', 650, 550, 800, 75, 'OTR-001'),
  ('LRC-033', '8000.50.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 700, 550, 850, 75, 'OTR-001'),
  ('LRC-034', '8000.51.01', 'INDEPENDENT_CONTRACTOR', 'Day Rate', 'Per Engagement', 650, 500, 800, 75, 'OTR-001'),
  ('LRC-035', '9000.52.01', 'VENDOR_SUPPLIED', 'Day Rate', 'Per Engagement', 850, 700, 1050, 75, 'OTR-001');

INSERT INTO emergency_code (code, label, emergency, swatch, sort_order) VALUES
  ('CODE_RED', 'Code Red', 'Fire Emergency', 'ecode-red', 1),
  ('CODE_ORANGE', 'Code Orange', 'Acts of Aggression', 'ecode-orange', 2),
  ('CODE_YELLOW', 'Code Yellow', 'Power or Structural Failure or Damage', 'ecode-yellow', 3),
  ('CODE_GREEN', 'Code Green', 'Theft & Loss Prevention', 'ecode-green', 4),
  ('CODE_BLUE', 'Code Blue', 'Medical Emergency', 'ecode-blue', 5),
  ('CODE_PURPLE', 'Code Purple', 'Political or Civil Unrest', 'ecode-purple', 6),
  ('CODE_WHITE', 'Code White', 'Government Agency Inspection or Encounter', 'ecode-white', 7),
  ('CODE_BLACK', 'Code Black', 'Acts of Terror', 'ecode-black', 8),
  ('CODE_PINK', 'Code Pink', 'Illegal Substance', 'ecode-pink', 9),
  ('CODE_INDIGO', 'Code Indigo', 'Absent or Missing Talent', 'ecode-indigo', 10),
  ('CODE_SILVER', 'Code Silver', 'Active Shooter', 'ecode-silver', 11),
  ('CODE_GREY', 'Code Grey', 'Bomb Threat', 'ecode-grey', 12),
  ('CODE_AMBER', 'Code Amber', 'Security Breach', 'ecode-amber', 13),
  ('CODE_ADAM', 'Code Adam', 'Missing Person(s)', 'ecode-adam', 14);

INSERT INTO operational_domain (domain, sort_order) VALUES
  ('Site Operations', 1),
  ('Stage Operations', 2),
  ('Food & Beverage Operations', 3),
  ('Guest Experience', 4),
  ('Back of House Operations', 5),
  ('Front of House Operations', 6);

INSERT INTO emergency_protocol (record_key, code, domain) VALUES
  ('EMG-001', 'CODE_RED', 'Site Operations'),
  ('EMG-002', 'CODE_RED', 'Stage Operations'),
  ('EMG-003', 'CODE_RED', 'Food & Beverage Operations'),
  ('EMG-004', 'CODE_RED', 'Guest Experience'),
  ('EMG-005', 'CODE_RED', 'Back of House Operations'),
  ('EMG-006', 'CODE_RED', 'Front of House Operations'),
  ('EMG-007', 'CODE_ORANGE', 'Site Operations'),
  ('EMG-008', 'CODE_ORANGE', 'Stage Operations'),
  ('EMG-009', 'CODE_ORANGE', 'Food & Beverage Operations'),
  ('EMG-010', 'CODE_ORANGE', 'Guest Experience'),
  ('EMG-011', 'CODE_ORANGE', 'Back of House Operations'),
  ('EMG-012', 'CODE_ORANGE', 'Front of House Operations'),
  ('EMG-013', 'CODE_YELLOW', 'Site Operations'),
  ('EMG-014', 'CODE_YELLOW', 'Stage Operations'),
  ('EMG-015', 'CODE_YELLOW', 'Food & Beverage Operations'),
  ('EMG-016', 'CODE_YELLOW', 'Guest Experience'),
  ('EMG-017', 'CODE_YELLOW', 'Back of House Operations'),
  ('EMG-018', 'CODE_YELLOW', 'Front of House Operations'),
  ('EMG-019', 'CODE_GREEN', 'Site Operations'),
  ('EMG-020', 'CODE_GREEN', 'Stage Operations'),
  ('EMG-021', 'CODE_GREEN', 'Food & Beverage Operations'),
  ('EMG-022', 'CODE_GREEN', 'Guest Experience'),
  ('EMG-023', 'CODE_GREEN', 'Back of House Operations'),
  ('EMG-024', 'CODE_GREEN', 'Front of House Operations'),
  ('EMG-025', 'CODE_BLUE', 'Site Operations'),
  ('EMG-026', 'CODE_BLUE', 'Stage Operations'),
  ('EMG-027', 'CODE_BLUE', 'Food & Beverage Operations'),
  ('EMG-028', 'CODE_BLUE', 'Guest Experience'),
  ('EMG-029', 'CODE_BLUE', 'Back of House Operations'),
  ('EMG-030', 'CODE_BLUE', 'Front of House Operations'),
  ('EMG-031', 'CODE_PURPLE', 'Site Operations'),
  ('EMG-032', 'CODE_PURPLE', 'Stage Operations'),
  ('EMG-033', 'CODE_PURPLE', 'Food & Beverage Operations'),
  ('EMG-034', 'CODE_PURPLE', 'Guest Experience'),
  ('EMG-035', 'CODE_PURPLE', 'Back of House Operations'),
  ('EMG-036', 'CODE_PURPLE', 'Front of House Operations'),
  ('EMG-037', 'CODE_WHITE', 'Site Operations'),
  ('EMG-038', 'CODE_WHITE', 'Stage Operations'),
  ('EMG-039', 'CODE_WHITE', 'Food & Beverage Operations'),
  ('EMG-040', 'CODE_WHITE', 'Guest Experience'),
  ('EMG-041', 'CODE_WHITE', 'Back of House Operations'),
  ('EMG-042', 'CODE_WHITE', 'Front of House Operations'),
  ('EMG-043', 'CODE_BLACK', 'Site Operations'),
  ('EMG-044', 'CODE_BLACK', 'Stage Operations'),
  ('EMG-045', 'CODE_BLACK', 'Food & Beverage Operations'),
  ('EMG-046', 'CODE_BLACK', 'Guest Experience'),
  ('EMG-047', 'CODE_BLACK', 'Back of House Operations'),
  ('EMG-048', 'CODE_BLACK', 'Front of House Operations'),
  ('EMG-049', 'CODE_PINK', 'Site Operations'),
  ('EMG-050', 'CODE_PINK', 'Stage Operations'),
  ('EMG-051', 'CODE_PINK', 'Food & Beverage Operations'),
  ('EMG-052', 'CODE_PINK', 'Guest Experience'),
  ('EMG-053', 'CODE_PINK', 'Back of House Operations'),
  ('EMG-054', 'CODE_PINK', 'Front of House Operations'),
  ('EMG-055', 'CODE_INDIGO', 'Site Operations'),
  ('EMG-056', 'CODE_INDIGO', 'Stage Operations'),
  ('EMG-057', 'CODE_INDIGO', 'Food & Beverage Operations'),
  ('EMG-058', 'CODE_INDIGO', 'Guest Experience'),
  ('EMG-059', 'CODE_INDIGO', 'Back of House Operations'),
  ('EMG-060', 'CODE_INDIGO', 'Front of House Operations'),
  ('EMG-061', 'CODE_SILVER', 'Site Operations'),
  ('EMG-062', 'CODE_SILVER', 'Stage Operations'),
  ('EMG-063', 'CODE_SILVER', 'Food & Beverage Operations'),
  ('EMG-064', 'CODE_SILVER', 'Guest Experience'),
  ('EMG-065', 'CODE_SILVER', 'Back of House Operations'),
  ('EMG-066', 'CODE_SILVER', 'Front of House Operations'),
  ('EMG-067', 'CODE_GREY', 'Site Operations'),
  ('EMG-068', 'CODE_GREY', 'Stage Operations'),
  ('EMG-069', 'CODE_GREY', 'Food & Beverage Operations'),
  ('EMG-070', 'CODE_GREY', 'Guest Experience'),
  ('EMG-071', 'CODE_GREY', 'Back of House Operations'),
  ('EMG-072', 'CODE_GREY', 'Front of House Operations'),
  ('EMG-073', 'CODE_AMBER', 'Site Operations'),
  ('EMG-074', 'CODE_AMBER', 'Stage Operations'),
  ('EMG-075', 'CODE_AMBER', 'Food & Beverage Operations'),
  ('EMG-076', 'CODE_AMBER', 'Guest Experience'),
  ('EMG-077', 'CODE_AMBER', 'Back of House Operations'),
  ('EMG-078', 'CODE_AMBER', 'Front of House Operations'),
  ('EMG-079', 'CODE_ADAM', 'Site Operations'),
  ('EMG-080', 'CODE_ADAM', 'Stage Operations'),
  ('EMG-081', 'CODE_ADAM', 'Food & Beverage Operations'),
  ('EMG-082', 'CODE_ADAM', 'Guest Experience'),
  ('EMG-083', 'CODE_ADAM', 'Back of House Operations'),
  ('EMG-084', 'CODE_ADAM', 'Front of House Operations');

INSERT INTO emergency_protocol_step (record_key, step_no, body) VALUES
  ('EMG-001', 1, 'Identify fire source and immediately activate fire extinguishers.'),
  ('EMG-001', 2, 'Contact {fire}.'),
  ('EMG-001', 3, 'Clear and cordon off affected areas.'),
  ('EMG-001', 4, 'Shut off utilities (gas/electric).'),
  ('EMG-002', 1, 'Immediately cut power to stage equipment to prevent electrical fires.'),
  ('EMG-002', 2, 'Use extinguishers near stage if safe to do so.'),
  ('EMG-002', 3, 'Assist with evacuation of performers and crew.'),
  ('EMG-003', 1, 'Cease all operations.'),
  ('EMG-003', 2, 'Turn off cooking equipment.'),
  ('EMG-003', 3, 'Instruct staff to guide guests out safely.'),
  ('EMG-003', 4, 'Evacuate food areas and ensure propane tanks are turned off.'),
  ('EMG-004', 1, 'Direct guests to nearest exits.'),
  ('EMG-004', 2, 'Make PA announcements, if possible, to ensure orderly evacuation.'),
  ('EMG-004', 3, 'Assist guests with limited mobility or special needs.'),
  ('EMG-005', 1, 'Ensure artists and performers are safely escorted off stage/backstage.'),
  ('EMG-005', 2, 'Secure props and valuable equipment backstage to prevent further hazards.'),
  ('EMG-006', 1, 'Ensure all exits are accessible and open.'),
  ('EMG-006', 2, 'Assist in the evacuation of high-capacity zones, including VIP and public areas.'),
  ('EMG-006', 3, 'Provide basic first aid if needed.'),
  ('EMG-007', 1, 'Alert security teams and {lawEnforcement} immediately.'),
  ('EMG-007', 2, 'Isolate aggressors and provide crowd control to prevent escalation.'),
  ('EMG-007', 3, 'Assess if evacuation is necessary.'),
  ('EMG-008', 1, 'Turn off stage lighting and sound to avoid escalating tensions.'),
  ('EMG-008', 2, 'If necessary, pause performances and lock down stage access.'),
  ('EMG-009', 1, 'Cease alcohol sales.'),
  ('EMG-009', 2, 'Instruct staff to close registers and secure high-value items.'),
  ('EMG-009', 3, 'Secure equipment that can be used as weapons (e.g., knives, utensils).'),
  ('EMG-010', 1, 'Move guests away from the conflict area, using calm and non-confrontational communication.'),
  ('EMG-010', 2, 'Offer assistance to frightened or injured guests.'),
  ('EMG-011', 1, 'Backstage personnel to remain alert and report suspicious behavior.'),
  ('EMG-011', 2, 'Provide a safe room for artists if aggression occurs near performance area.'),
  ('EMG-012', 1, 'Assist security teams with crowd control and ensure that aggressors are contained away from general public.'),
  ('EMG-012', 2, 'Coordinate with medical teams if injuries occur.'),
  ('EMG-013', 1, 'Cut power to affected areas.'),
  ('EMG-013', 2, 'Inspect any visible structural damage (e.g., lighting rigs, barricades).'),
  ('EMG-013', 3, 'Work with electricians to restore power safely.'),
  ('EMG-014', 1, 'Secure all stage equipment and instruments to prevent further damage.'),
  ('EMG-014', 2, 'Pause performances and make an announcement explaining the situation.'),
  ('EMG-015', 1, 'Stop food prep to avoid injury.'),
  ('EMG-015', 2, 'If structural damage affects tents/kiosks, direct guests and staff to clear the area.'),
  ('EMG-016', 1, 'Calm guests and offer clear instructions to avoid panic.'),
  ('EMG-016', 2, 'Guide guests to alternate exits if structural damage affects egress routes.'),
  ('EMG-017', 1, 'Ensure that artists are safe backstage and equipment is not at risk of being damaged.'),
  ('EMG-017', 2, 'Organize personnel to inspect and report any damage in restricted areas.'),
  ('EMG-018', 1, 'Guide guests to safety and inform them of alternative actions (delays or cancellations).'),
  ('EMG-018', 2, 'Assist in directing crowds away from dangerous areas.'),
  ('EMG-019', 1, 'Increase security patrols in sensitive areas (e.g., entrances, high-traffic areas).'),
  ('EMG-019', 2, 'Report all thefts to {lawEnforcement}.'),
  ('EMG-019', 3, 'Conduct bag checks at exits, if needed.'),
  ('EMG-020', 1, 'Secure all stage equipment, especially high-value instruments or electronics.'),
  ('EMG-020', 2, 'Coordinate with security to monitor artist equipment and dressing rooms.'),
  ('EMG-021', 1, 'Lock down cash registers and remove high-value items from view.'),
  ('EMG-021', 2, 'Report suspicious behavior to security.'),
  ('EMG-021', 3, 'Implement a strict cash-handling procedure.'),
  ('EMG-022', 1, 'Assist guests in filing lost or stolen property reports.'),
  ('EMG-022', 2, 'Use public announcements to inform guests of the incident, if needed.'),
  ('EMG-023', 1, 'Secure personal and valuable equipment for artists and performers.'),
  ('EMG-023', 2, 'Monitor access to VIP areas to prevent unauthorized entry.'),
  ('EMG-024', 1, 'Assist security in ensuring all exits are covered.'),
  ('EMG-024', 2, 'Implement crowd control to prevent thefts during egress.'),
  ('EMG-024', 3, 'Handle guest complaints regarding lost items.'),
  ('EMG-025', 1, 'Immediately call {ems} or direct on-site medical personnel.'),
  ('EMG-025', 2, 'Clear space for medical teams to access the affected individual.'),
  ('EMG-025', 3, 'Use first aid kits if necessary.'),
  ('EMG-026', 1, 'Pause performance to direct attention to the medical emergency.'),
  ('EMG-026', 2, 'Keep communication channels open to ensure paramedics can access the stage area.'),
  ('EMG-027', 1, 'Offer water or basic care (if applicable).'),
  ('EMG-027', 2, 'Instruct staff to guide {ems} to the food area if needed.'),
  ('EMG-028', 1, 'Alert guests to make way for medical personnel.'),
  ('EMG-028', 2, 'Provide support to affected individuals until {ems} arrives.'),
  ('EMG-029', 1, 'Ensure performers and crew are safe and are not obstructing medical responders.'),
  ('EMG-029', 2, 'Provide medics with direct access to the backstage area if needed.'),
  ('EMG-030', 1, 'Coordinate with medical teams to facilitate access to emergency locations.'),
  ('EMG-030', 2, 'Keep guests informed about delays or disruptions due to the emergency.'),
  ('EMG-031', 1, 'Activate emergency protocol and increase security presence.'),
  ('EMG-031', 2, 'Prepare evacuation routes and ensure exits are clear.'),
  ('EMG-031', 3, 'Work with {lawEnforcement} for guidance and assistance.'),
  ('EMG-032', 1, 'Stop the performance to prevent escalation.'),
  ('EMG-032', 2, 'Secure stage and assist in evacuating performers and staff to a safe area.'),
  ('EMG-033', 1, 'Lock down all kiosks, close food prep areas.'),
  ('EMG-033', 2, 'Move staff to safe areas and prepare for evacuation.'),
  ('EMG-034', 1, 'Calm guests and direct them to safety if evacuation becomes necessary.'),
  ('EMG-034', 2, 'Provide real-time updates using PA system or megaphones.'),
  ('EMG-035', 1, 'Ensure artists are safely escorted off-site if necessary.'),
  ('EMG-035', 2, 'Secure dressing rooms and valuables.'),
  ('EMG-036', 1, 'Assist in managing crowds to prevent disorder.'),
  ('EMG-036', 2, 'Ensure clear communication with guests, informing them about actions being taken for their safety.'),
  ('EMG-037', 1, 'Provide requested permits, licenses, and compliance documentation to the agency.'),
  ('EMG-037', 2, 'Ensure all areas meet safety standards (fire exits, lighting, structural integrity).'),
  ('EMG-038', 1, 'Pause the performance if requested by officials.'),
  ('EMG-038', 2, 'Ensure all stage operations are compliant with safety regulations (sound levels, rigging).'),
  ('EMG-039', 1, 'Provide food handling permits, alcohol licenses, and health inspection certificates upon request.'),
  ('EMG-040', 1, 'Inform guests of any temporary delays due to inspections.'),
  ('EMG-040', 2, 'Provide support to guests and reassure them that the event is in compliance with safety protocols.'),
  ('EMG-041', 1, 'Ensure back-of-house areas meet safety regulations and provide access to officials for inspections.'),
  ('EMG-041', 2, 'Maintain communication with event management.'),
  ('EMG-042', 1, 'Assist in ensuring that front-of-house operations meet health, safety, and accessibility regulations.'),
  ('EMG-042', 2, 'Provide compliance documentation to authorities if required.'),
  ('EMG-043', 1, 'Immediately contact {lawEnforcement}, {fire}, and {federal}.'),
  ('EMG-043', 2, 'Activate emergency evacuation protocols.'),
  ('EMG-043', 3, 'Secure all entrances and exits.'),
  ('EMG-044', 1, 'Cut stage power and lighting to avoid panic.'),
  ('EMG-044', 2, 'Assist security in evacuating artists and crew to secure areas.'),
  ('EMG-045', 1, 'Cease all operations and secure food stands.'),
  ('EMG-045', 2, 'Ensure that all dangerous equipment (e.g., propane tanks) is turned off and locked down.'),
  ('EMG-046', 1, 'Announce evacuation instructions clearly and calmly.'),
  ('EMG-046', 2, 'Assist guests with disabilities or mobility challenges in evacuating.'),
  ('EMG-047', 1, 'Secure VIP and performer areas to prevent unauthorized access.'),
  ('EMG-047', 2, 'Escort artists and staff to safety through pre-established emergency routes.'),
  ('EMG-048', 1, 'Ensure all exit points are secure but accessible for a controlled evacuation.'),
  ('EMG-048', 2, 'Provide first aid support if necessary.'),
  ('EMG-049', 1, 'Report substance use to security and law enforcement.'),
  ('EMG-049', 2, 'Assist in monitoring suspicious activity and help contain the situation.'),
  ('EMG-050', 1, 'Halt the performance and coordinate with security if illicit substances are suspected backstage.'),
  ('EMG-050', 2, 'Maintain communication with artists and crew regarding safety.'),
  ('EMG-051', 1, 'Cease alcohol sales and report any incidents of illegal substance use near food stations.'),
  ('EMG-051', 2, 'Monitor guests for signs of intoxication and report to security.'),
  ('EMG-052', 1, 'Report any suspicious activity to security.'),
  ('EMG-052', 2, 'Assist guests in reporting concerns related to substance use or safety.'),
  ('EMG-053', 1, 'Ensure backstage areas are free of illegal substances and report any issues to management and law enforcement.'),
  ('EMG-054', 1, 'Alert security and provide support for guests affected by substance use.'),
  ('EMG-054', 2, 'Ensure that proper protocols for dealing with intoxicated guests are followed.'),
  ('EMG-055', 1, 'Contact talent management immediately to locate missing talent.'),
  ('EMG-055', 2, 'Coordinate with other departments to adjust schedules as necessary.'),
  ('EMG-056', 1, 'Delay performance and provide alternate acts or entertainment, if possible.'),
  ('EMG-056', 2, 'Ensure that backup performers are ready to take the stage if needed.'),
  ('EMG-057', 1, 'Adjust food and beverage schedules to account for possible delays or cancellations.'),
  ('EMG-057', 2, 'Inform staff of changes in the performance schedule.'),
  ('EMG-058', 1, 'Inform guests of any delays or changes in performances through the PA system.'),
  ('EMG-058', 2, 'Provide alternative forms of entertainment or services, if possible.'),
  ('EMG-059', 1, 'Work with talent agents to locate the missing artist.'),
  ('EMG-059', 2, 'Prepare alternate accommodations for talent if transportation issues are causing delays.'),
  ('EMG-060', 1, 'Ensure all front-of-house staff are informed of changes.'),
  ('EMG-060', 2, 'Coordinate guest services to handle inquiries and possible complaints about the missing act.'),
  ('EMG-061', 1, 'Immediately notify {lawEnforcement} and security personnel.'),
  ('EMG-061', 2, 'Lock down all entrances and exits.'),
  ('EMG-061', 3, 'Instruct staff to move guests to pre-designated secure areas or evacuate.'),
  ('EMG-062', 1, 'Cut stage lights and sound to reduce visibility and prevent panic.'),
  ('EMG-062', 2, 'Ensure performers are evacuated to safe areas backstage.'),
  ('EMG-063', 1, 'Cease operations and direct staff to secure food areas.'),
  ('EMG-063', 2, 'Lock down all exits from food tents and kiosks.'),
  ('EMG-064', 1, 'Calmly guide guests to secure areas or nearest exits as directed by security.'),
  ('EMG-064', 2, 'Help guests find shelter in place if an evacuation is not immediately possible.'),
  ('EMG-065', 1, 'Secure VIP and backstage areas.'),
  ('EMG-065', 2, 'Help performers evacuate through secure routes or lock down in safe areas.'),
  ('EMG-066', 1, 'Direct guests toward exits and assist law enforcement with crowd control.'),
  ('EMG-066', 2, 'Provide medical support for any injuries.'),
  ('EMG-067', 1, 'Notify {lawEnforcement} and {bombSquad} immediately.'),
  ('EMG-067', 2, 'Clear and evacuate areas as directed by law enforcement.'),
  ('EMG-067', 3, 'Avoid using radios or cell phones in case of detonation risk.'),
  ('EMG-068', 1, 'Secure all stage equipment and evacuate performers and crew to safe areas.'),
  ('EMG-068', 2, 'Work with authorities to ensure proper procedures are followed for bomb threat investigation.'),
  ('EMG-069', 1, 'Cease operations and evacuate staff to designated safety areas.'),
  ('EMG-069', 2, 'Secure propane tanks and any flammable materials.'),
  ('EMG-070', 1, 'Calmly announce evacuation procedures and direct guests to exits without causing panic.'),
  ('EMG-070', 2, 'Assist guests with disabilities or limited mobility.'),
  ('EMG-071', 1, 'Evacuate backstage personnel to safe areas.'),
  ('EMG-071', 2, 'Ensure that performers are kept in secure locations until further instruction from law enforcement.'),
  ('EMG-072', 1, 'Ensure all exits are accessible for rapid evacuation.'),
  ('EMG-072', 2, 'Assist law enforcement with crowd control and provide medical support as needed.'),
  ('EMG-073', 1, 'Notify security and lock down vulnerable access points.'),
  ('EMG-073', 2, 'Assist security in managing crowds and preventing unauthorized individuals from entering secure areas.'),
  ('EMG-074', 1, 'Lock down stage access and evacuate performers if necessary.'),
  ('EMG-074', 2, 'Secure valuable stage equipment.'),
  ('EMG-075', 1, 'Shut down food operations and secure high-value items.'),
  ('EMG-075', 2, 'Assist security in monitoring access points to prevent unauthorized entry.'),
  ('EMG-076', 1, 'Reassure guests and prevent panic.'),
  ('EMG-076', 2, 'Move guests away from the area of the breach to safer locations.'),
  ('EMG-077', 1, 'Secure backstage areas, ensuring unauthorized personnel do not access dressing rooms or restricted zones.'),
  ('EMG-078', 1, 'Secure all exits and entry points to prevent unauthorized access.'),
  ('EMG-078', 2, 'Coordinate with security and local law enforcement to handle breach.'),
  ('EMG-079', 1, 'Alert security and event management.'),
  ('EMG-079', 2, 'Assist with immediate searches using pre-assigned personnel.'),
  ('EMG-079', 3, 'Make announcements over PA system or use digital alerts.'),
  ('EMG-080', 1, 'Suspend performance temporarily if necessary to coordinate searches.'),
  ('EMG-080', 2, 'Ensure all stage staff are briefed on the missing person situation.'),
  ('EMG-081', 1, 'Instruct food and beverage staff to monitor exits and inform security if the missing person is seen.'),
  ('EMG-082', 1, 'Assist in locating missing individuals by directing security or offering descriptions to staff.'),
  ('EMG-082', 2, 'Guide guardians to a secure meeting point.'),
  ('EMG-083', 1, 'Help secure backstage areas and prevent unauthorized personnel from entering.'),
  ('EMG-083', 2, 'Assist in search efforts by monitoring restricted areas.'),
  ('EMG-084', 1, 'Coordinate with law enforcement and search teams to monitor exits.'),
  ('EMG-084', 2, 'Assist with family reunification processes.');

INSERT INTO agency_function (function, label, responder, sort_order) VALUES
  ('fire', 'Fire', true, 1),
  ('ems', 'EMS', true, 2),
  ('lawEnforcement', 'Law Enforcement', true, 3),
  ('bombSquad', 'Bomb Squad', true, 4),
  ('federal', 'Federal', true, 5),
  ('building', 'Building', false, 6),
  ('health', 'Health', false, 7),
  ('occupationalSafety', 'Occupational Safety', false, 8);

INSERT INTO wage_hour_rule (jurisdiction_id, source, weekly_ot_after_hours, daily_ot_after_hours, daily_dt_after_hours, min_ot_multiplier, min_dt_multiplier) VALUES
  ('US', 'Fair Labor Standards Act, 29 U.S.C. 207', 40, NULL, NULL, 1.5, NULL);

INSERT INTO jurisdiction_agency (jurisdiction_id, function, agency, contact) VALUES
  ('US-FL-MIAMI-DADE', 'fire', 'Miami Fire-Rescue', '911'),
  ('US-FL-MIAMI-DADE', 'ems', 'Miami Fire-Rescue', '911'),
  ('US-FL-MIAMI-DADE', 'lawEnforcement', 'Miami Police Department', '911'),
  ('US-FL-MIAMI-DADE', 'building', 'City of Miami Building Department', NULL),
  ('US-FL-MIAMI-DADE', 'health', 'Florida Department of Health', NULL),
  ('US-FL-MIAMI-DADE', 'occupationalSafety', 'Occupational Safety and Health Administration', NULL);

INSERT INTO organization_type (label) VALUES
  ('For-Profit'),
  ('Nonprofit'),
  ('Public Agency');

INSERT INTO classification_organization_type (worker_classification, organization_type) VALUES
  ('EMPLOYEE', 'For-Profit'),
  ('EMPLOYEE', 'Nonprofit'),
  ('EMPLOYEE', 'Public Agency'),
  ('INDEPENDENT_CONTRACTOR', 'For-Profit'),
  ('INDEPENDENT_CONTRACTOR', 'Nonprofit'),
  ('INDEPENDENT_CONTRACTOR', 'Public Agency'),
  ('VENDOR_SUPPLIED', 'For-Profit'),
  ('VENDOR_SUPPLIED', 'Nonprofit'),
  ('VENDOR_SUPPLIED', 'Public Agency'),
  ('UNPAID_INTERN', 'For-Profit'),
  ('UNPAID_INTERN', 'Nonprofit'),
  ('UNPAID_INTERN', 'Public Agency'),
  ('VOLUNTEER', 'Nonprofit'),
  ('VOLUNTEER', 'Public Agency');
