/**
 * Safety (Sections 4.2 and 7.4): inspections, the permit engine, incidents with dispatch,
 * emergency codes and the radio plan. Medical encounter notes are Restricted.
 */
import * as c from "../common/canon-codes.ts";
import * as f from "../common/fields.ts";
import { defineResource } from "../common/resource.ts";

export const InspectionTemplate = defineResource({
  name: "InspectionTemplate",
  table: "app.inspection_templates",
  description: "A template for an inspection walk.",
  fields: {
    name: f.text("Template name.", "Daily Stage Walk"),
    tag_id: c.TagId.nullable(),
  },
});

export const InspectionItem = defineResource({
  name: "InspectionItem",
  table: "app.inspection_items",
  description: "An item of an inspection template.",
  immutable: ["inspection_template_id"],
  fields: {
    inspection_template_id: f.ref("inspection template"),
    position: f.int("Item order.", 1, 1),
    prompt: f.text("What to check.", "Guardrails secured on all stage edges"),
    requires_photo: f.bool("Whether a photo is required.", true),
  },
});

export const Inspection = defineResource({
  name: "Inspection",
  table: "app.inspections",
  description: "An inspection performed from a template, with sign-off.",
  immutable: ["inspection_template_id", "project_id"],
  serverSet: ["inspection_state", "signed_off_by", "signed_off_at"],
  fields: {
    project_id: f.ref("project"),
    inspection_template_id: f.ref("inspection template"),
    zone_id: f.ref("zone").nullable(),
    inspector_id: f.ref("inspector"),
    inspection_state: f.stateLabel("Inspection state.", "Active"),
    signed_off_by: f.ref("person who signed off").nullable(),
    signed_off_at: f.instant("When it was signed off.").nullable(),
  },
});

export const InspectionResult = defineResource({
  name: "InspectionResult",
  table: "app.inspection_results",
  description: "Pass or fail for one inspection item.",
  immutable: ["inspection_id", "inspection_item_id"],
  fields: {
    inspection_id: f.ref("inspection"),
    inspection_item_id: f.ref("inspection item"),
    passed: f.bool("Whether the item passed.", true),
    notes: f.longText("Notes.", "Left rail tightened on site.").nullable(),
    photo_document_id: f.ref("photo").nullable(),
  },
});

export const PermitRequirement = defineResource({
  name: "PermitRequirement",
  table: "app.permit_requirements",
  description:
    "A permit requirement generated by the jurisdiction permit engine. An unpopulated jurisdiction returns no answer.",
  serverSet: ["project_id", "rule", "jurisdiction_id", "permit", "ahj", "due_on", "permit_state"],
  fields: {
    project_id: f.ref("project"),
    rule: f.text("Canon permit rule that triggered it.", "Assembly occupancy"),
    jurisdiction_id: c.JurisdictionId,
    permit: f.text("Permit required.", "Certificate of occupancy"),
    ahj: f.text("Authority having jurisdiction.", "City Building and Fire"),
    due_on: f.date("Latest filing date from the lead time.").nullable(),
    permit_state: f.stateLabel("Permit state.", "Proposed"),
  },
});

export const Incident = defineResource({
  name: "Incident",
  table: "app.incidents",
  description:
    "An incident with dispatch. A critical incident cannot be relabeled and closed in one statement; closing requires sign-off.",
  immutable: ["project_id"],
  serverSet: ["incident_state", "incident_number"],
  fields: {
    project_id: f.ref("project"),
    incident_number: f.code("Incident number.", "INC-0042"),
    severity: f.stateLabel("Severity.", "Critical"),
    title: f.text("Short description.", "Guest Fall Near North Bar"),
    occurred_at: f.instant("When it happened."),
    zone_id: f.ref("zone").nullable(),
    latitude: f.latitude().nullable(),
    longitude: f.longitude().nullable(),
    incident_state: f.stateLabel("Incident state.", "Active"),
    emergency_code_id: f.ref("emergency code").nullable(),
  },
});

export const IncidentParty = defineResource({
  name: "IncidentParty",
  table: "app.incident_parties",
  description: "A person involved in an incident.",
  immutable: ["incident_id"],
  fields: {
    incident_id: f.ref("incident"),
    person_id: f.ref("involved person").nullable(),
    involvement: f.stateLabel("Involvement.", "Witness"),
    name_if_unknown: f
      .text("Name when the person has no record.", "Guest, name withheld")
      .nullable(),
  },
});

export const IncidentMedia = defineResource({
  name: "IncidentMedia",
  table: "app.incident_media",
  description: "A photo or file attached to an incident.",
  immutable: ["incident_id", "document_id"],
  fields: { incident_id: f.ref("incident"), document_id: f.ref("media document") },
});

export const DispatchAssignment = defineResource({
  name: "DispatchAssignment",
  table: "app.dispatch_assignments",
  description: "A responder dispatched to an incident.",
  immutable: ["incident_id"],
  fields: {
    incident_id: f.ref("incident"),
    responder_id: f.ref("responder"),
    dispatched_at: f.instant("When the responder was dispatched."),
    arrived_at: f.instant("When the responder arrived.").nullable(),
    cleared_at: f.instant("When the responder cleared.").nullable(),
  },
});

export const MedicalEncounter = defineResource({
  name: "MedicalEncounter",
  table: "app.medical_encounters",
  description: "A medical encounter. Notes are Restricted, encrypted and never sent to a model.",
  immutable: ["incident_id"],
  restricted: ["notes"],
  fields: {
    incident_id: f.ref("incident"),
    treated_by: f.ref("treating medic"),
    disposition: f.stateLabel("Disposition.", "Treated And Released"),
    notes: f.longText("Clinical notes.", "Abrasion to the left knee, cleaned and dressed."),
  },
});

export const CrisisAlert = defineResource({
  name: "CrisisAlert",
  table: "app.crisis_alerts",
  description: "A crisis alert broadcast to a project.",
  immutable: ["project_id"],
  fields: {
    project_id: f.ref("project"),
    emergency_code_id: f.ref("emergency code"),
    message: f.text("Alert message.", "Weather hold: clear the north lawn."),
    issued_at: f.instant("When the alert was issued."),
    cleared_at: f.instant("When the alert was cleared.").nullable(),
  },
});

export const EmergencyCode = defineResource({
  name: "EmergencyCode",
  table: "app.emergency_codes",
  description:
    "An org emergency code, seeded from the Standard Library and listed in numeric order.",
  fields: {
    code: f.code("Emergency code.", "10"),
    name: f.text("Code name.", "Medical Assist"),
    response: f.longText("Response procedure.", "Dispatch the medical team to the location."),
  },
});

export const RadioChannel = defineResource({
  name: "RadioChannel",
  table: "app.radio_channels",
  description: "A radio channel in the org radio plan, listed in numeric order.",
  fields: {
    channel: f.int("Channel number.", 1, 1),
    name: f.text("Channel name.", "Production"),
    frequency_mhz: f.quantity("Frequency in MHz.", 462.5625).nullable(),
    project_id: f.ref("project").nullable(),
  },
});
