import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { countFailures, validateCounts } from "./counts.ts";
import type { CountResult } from "./counts.ts";
import { Findings } from "./doctrine.ts";
import type { LoadedInputs } from "./inputs.ts";
import { buildCanonModel } from "./model/bible-model.ts";
import type { RepoPaths } from "./paths.ts";
import { CANON_TABLES } from "./schema/canon-tables.ts";
import { GOVERNANCE_TABLES } from "./schema/governance-tables.ts";
import type { TableSpec } from "./schema/types.ts";
import { insertStatements, tableDdl } from "./sql.ts";
import type { SqlRow } from "./sql.ts";

/** Every generated artifact as path (relative to the repository root) and content. */
export interface GeneratedFile {
  readonly path: string;
  readonly content: string;
  /** Committed outputs must be byte-identical on re-run; reports are not committed. */
  readonly committed: boolean;
}

export interface GenerateResult {
  readonly files: readonly GeneratedFile[];
  readonly counts: readonly CountResult[];
  readonly findings: Findings;
  readonly tables: ReadonlyMap<string, readonly SqlRow[]>;
}

export const SCHEMA_TABLES: readonly TableSpec[] = [...CANON_TABLES, ...GOVERNANCE_TABLES];

const GENERATED_NOTE =
  "-- Generated by @xos/canon-import from canon/source. Do not edit by hand: change the canon\n" +
  "-- files or the importer and run `pnpm --filter @xos/canon-import canon:generate`.\n";

export function tablesMigration(
  tables: readonly TableSpec[],
  name: string,
  purpose: string,
): string {
  const body = tables.map(tableDdl).join("\n");
  return `-- ${name}\n${GENERATED_NOTE}-- ${purpose}\n\n${body}`;
}

export function seedMigration(
  tables: readonly TableSpec[],
  rows: ReadonlyMap<string, readonly SqlRow[]>,
  findings: Findings,
  name: string,
  purpose: string,
): string {
  const parts = tables.map((t) => {
    const r = rows.get(t.name);
    if (r === undefined) throw new Error(`No seed rows were built for xpms.${t.name}`);
    return `-- xpms.${t.name}: ${r.length} rows\n${insertStatements({ table: t, rows: r }, findings)}`;
  });
  return `-- ${name}\n${GENERATED_NOTE}-- ${purpose}\n\n${parts.join("\n")}`;
}

export function generateCanon(inputs: LoadedInputs): GenerateResult {
  const findings = new Findings();
  const model = buildCanonModel(
    {
      bible: inputs.bible,
      itemCatalog: inputs.itemCatalog,
      glChart: inputs.glChart,
      files: inputs.sha,
    },
    findings,
  );
  if (model.problems.length > 0) {
    throw new Error(`Canon import stopped:\n${model.problems.join("\n")}`);
  }
  const counts = validateCounts(model.counts, model.generated);
  const failures = countFailures(counts);
  if (failures.length > 0) throw new Error(`Canon counts do not validate:\n${failures.join("\n")}`);

  const tables = new Map<string, readonly SqlRow[]>(model.tables);
  tables.set("intake", model.intake);

  const files: GeneratedFile[] = [
    {
      path: "supabase/migrations/0101_xpms_tables.sql",
      content: tablesMigration(
        SCHEMA_TABLES,
        "0101_xpms_tables.sql",
        "Canon dimensions, catalog, bridges and governance tables (Section 7.2), with a comment on every table and column.",
      ),
      committed: true,
    },
    {
      path: "supabase/migrations/0150_xpms_canon_seed.sql",
      content: seedMigration(
        SCHEMA_TABLES,
        tables,
        findings,
        "0150_xpms_canon_seed.sql",
        "Canon seed from the XOS 4.0 Bible, Item Catalog CSV and GL chart CSV, counts validated.",
      ),
      committed: true,
    },
  ];
  return { files, counts, findings, tables };
}

export function writeGenerated(paths: RepoPaths, files: readonly GeneratedFile[]): void {
  for (const f of files) {
    const target = join(paths.root, f.path);
    mkdirSync(join(target, ".."), { recursive: true });
    writeFileSync(target, f.content);
  }
}

/** Committed files whose content on disk differs from a fresh generation. */
export function staleFiles(paths: RepoPaths, files: readonly GeneratedFile[]): string[] {
  return files
    .filter((f) => f.committed)
    .filter((f) => {
      try {
        return readFileSync(join(paths.root, f.path), "utf8") !== f.content;
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return true;
        throw error;
      }
    })
    .map((f) => f.path);
}
