import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { countFailures, validateCounts } from "./counts.ts";
import type { CountResult } from "./counts.ts";
import { Findings } from "./doctrine.ts";
import type { LoadedInputs } from "./inputs.ts";
import { buildCanonModel } from "./model/bible-model.ts";
import type { RepoPaths } from "./paths.ts";
import { CANON_TABLES } from "./schema/canon-tables.ts";
import { GOVERNANCE_TABLES } from "./schema/governance-tables.ts";
import { REFERENCE_TABLES } from "./schema/reference-tables.ts";
import { readColumnMap } from "./playbook/column-map.ts";
import type { ColumnMap } from "./playbook/column-map.ts";
import { applyPlaybook } from "./playbook/model.ts";
import type { DiffEntry } from "./playbook/model.ts";
import { PLAYBOOK_TABLES, stdTableSpecs } from "./playbook/tables.ts";
import { compareWithReference, parseReferenceSeed } from "./reference.ts";
import type { ReferenceDiff } from "./reference.ts";
import { diffReport, doctrineReport, importReport } from "./reports.ts";
import type { TableSpec } from "./schema/types.ts";
import { insertStatements, tableDdl } from "./sql.ts";
import type { SqlRow } from "./sql.ts";

/** Every generated artifact as path (relative to the repository root) and content. */
export interface GeneratedFile {
  readonly path: string;
  readonly content: string;
  /** Committed outputs must be byte-identical on re-run; reports are not committed. */
  readonly committed: boolean;
}

export interface GenerateResult {
  readonly files: readonly GeneratedFile[];
  readonly counts: readonly CountResult[];
  readonly findings: Findings;
  readonly tables: ReadonlyMap<string, readonly SqlRow[]>;
  readonly diff: readonly DiffEntry[];
  readonly reference: readonly ReferenceDiff[];
  readonly report: readonly string[];
}

export const SCHEMA_TABLES: readonly TableSpec[] = [
  ...CANON_TABLES,
  ...REFERENCE_TABLES,
  ...GOVERNANCE_TABLES,
];

const GENERATED_NOTE =
  "-- Generated by @xos/canon-import from canon/source. Do not edit by hand: change the canon\n" +
  "-- files or the importer and run `pnpm --filter @xos/canon-import canon:generate`.\n";

export function tablesMigration(
  tables: readonly TableSpec[],
  name: string,
  purpose: string,
): string {
  const body = tables.map(tableDdl).join("\n");
  return `-- ${name}\n${GENERATED_NOTE}-- ${purpose}\n\n${body}`;
}

export function seedMigration(
  tables: readonly TableSpec[],
  rows: ReadonlyMap<string, readonly SqlRow[]>,
  findings: Findings,
  name: string,
  purpose: string,
): string {
  const parts = tables.map((t) => {
    const r = rows.get(t.name);
    if (r === undefined) throw new Error(`No seed rows were built for xpms.${t.name}`);
    return `-- xpms.${t.name}: ${r.length} rows\n${insertStatements({ table: t, rows: r }, findings)}`;
  });
  return `-- ${name}\n${GENERATED_NOTE}-- ${purpose}\n\n${parts.join("\n")}`;
}

export interface GenerateOptions {
  /** The completed column map. */
  readonly map: ColumnMap;
  /** The owner's reference seed, when present, for the reference model check. */
  readonly referenceSeed?: string;
}

export function generateCanon(inputs: LoadedInputs, options: GenerateOptions): GenerateResult {
  const findings = new Findings();
  const model = buildCanonModel(
    {
      bible: inputs.bible,
      itemCatalog: inputs.itemCatalog,
      rulings: inputs.rulings,
      glChart: inputs.glChart,
      files: inputs.sha,
    },
    findings,
  );
  if (model.problems.length > 0) {
    throw new Error(`Canon import stopped:\n${model.problems.join("\n")}`);
  }
  const counts = validateCounts(model.counts, model.generated);
  const failures = countFailures(counts);
  if (failures.length > 0) throw new Error(`Canon counts do not validate:\n${failures.join("\n")}`);

  const playbook = applyPlaybook(
    model.tables,
    model.intake,
    inputs.playbook,
    options.map,
    inputs.rulings,
    findings,
    inputs.sha.playbook,
  );
  const tables = new Map<string, readonly SqlRow[]>(playbook.tables);
  tables.set("intake", playbook.intake);
  const stdSpecs = stdTableSpecs(options.map);
  const seedTables = [
    ...CANON_TABLES,
    ...REFERENCE_TABLES,
    ...PLAYBOOK_TABLES,
    ...stdSpecs,
    ...GOVERNANCE_TABLES,
  ];
  const reference =
    options.referenceSeed === undefined
      ? []
      : compareWithReference(parseReferenceSeed(options.referenceSeed), tables);

  const seed = seedMigration(
    seedTables,
    tables,
    findings,
    "0150_xpms_canon_seed.sql",
    "Canon seed from the XOS 4.0 Bible, Item Catalog CSV, GL chart CSV, Production Playbook and the owner rulings, counts validated.",
  );
  const rowCounts = new Map<string, number>(
    seedTables.map((t) => [t.name, tables.get(t.name)?.length ?? 0]),
  );
  const files: GeneratedFile[] = [
    {
      path: "supabase/migrations/0101_xpms_tables.sql",
      content: tablesMigration(
        SCHEMA_TABLES,
        "0101_xpms_tables.sql",
        "Canon dimensions, catalog, bridges, the owner's reference model tables (decisions D11 to D17, D19) and governance (Section 7.2), with a comment on every table and column.",
      ),
      committed: true,
    },
    {
      path: "supabase/migrations/0105_xpms_playbook_tables.sql",
      content: tablesMigration(
        [...PLAYBOOK_TABLES, ...stdSpecs],
        "0105_xpms_playbook_tables.sql",
        "Playbook registry, Production Template and Standard Library tables (Section 2.1), defined by canon/map/playbook-columns.yaml.",
      ),
      committed: true,
    },
    { path: "supabase/migrations/0150_xpms_canon_seed.sql", content: seed, committed: true },
    {
      path: "canon/reports/doctrine-findings.md",
      content: doctrineReport(findings.items),
      committed: false,
    },
    {
      path: "canon/reports/playbook-bible-diff.md",
      content: diffReport(playbook.diff),
      committed: false,
    },
    {
      path: "canon/reports/migration-report.txt",
      content: `${playbook.report.join("\n")}\n`,
      committed: false,
    },
    {
      path: "canon/reports/import-report.md",
      content: importReport(counts, options.map, playbook.realWorld, reference, rowCounts),
      committed: false,
    },
  ];
  return {
    files,
    counts,
    findings,
    tables,
    diff: playbook.diff,
    reference,
    report: playbook.report,
  };
}

export const REFERENCE_SEED = "design/xos-design-system/export/canon/0101_xpms_canon_seed.sql";

/** The committed column map and, when the design export is present, the owner's reference seed. */
export function generateOptions(paths: RepoPaths): GenerateOptions {
  const map = readColumnMap(readFileSync(join(paths.canonMap, "playbook-columns.yaml"), "utf8"));
  const seedPath = join(paths.root, REFERENCE_SEED);
  return existsSync(seedPath) ? { map, referenceSeed: readFileSync(seedPath, "utf8") } : { map };
}

export function writeGenerated(paths: RepoPaths, files: readonly GeneratedFile[]): void {
  for (const f of files) {
    const target = join(paths.root, f.path);
    mkdirSync(join(target, ".."), { recursive: true });
    writeFileSync(target, f.content);
  }
}

/** Committed files whose content on disk differs from a fresh generation. */
export function staleFiles(paths: RepoPaths, files: readonly GeneratedFile[]): string[] {
  return files
    .filter((f) => f.committed)
    .filter((f) => {
      try {
        return readFileSync(join(paths.root, f.path), "utf8") !== f.content;
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return true;
        throw error;
      }
    })
    .map((f) => f.path);
}
