import type { CountResult } from "./counts.ts";
import type { Finding } from "./doctrine.ts";
import type { ColumnMap } from "./playbook/column-map.ts";
import { dispositionTotals } from "./playbook/column-map.ts";
import type { DiffEntry, RealWorldRow } from "./playbook/model.ts";
import type { ReferenceDiff } from "./reference.ts";

/** Generated reports under canon/reports (ignored by git; regenerated by every run). */

function cell(v: string | null): string {
  return (v ?? "(blank)").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export function doctrineReport(findings: readonly Finding[]): string {
  const kinds = [...new Set(findings.map((f) => f.kind))];
  const lines = [
    "# Doctrine findings",
    "",
    "Canon values the importer adjusted, could not resolve, or found in conflict. Each needs an owner decision; none was changed silently.",
    "",
  ];
  for (const k of kinds) {
    const items = findings.filter((f) => f.kind === k);
    lines.push(`## ${k} (${items.length})`, "", "| Location | Detail |", "| --- | --- |");
    for (const f of items) lines.push(`| ${cell(f.location)} | ${cell(f.detail)} |`);
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

export function diffReport(diff: readonly DiffEntry[]): string {
  const lines = [
    "# Playbook to Bible diff",
    "",
    "Every value where a Bible-mirrored Playbook sheet differs from canon, every row only one side holds, and every Standard Library conflict. Neither file silently wins: Playbook values wait in xpms.intake for the owner.",
    "",
  ];
  const groups = new Map<string, DiffEntry[]>();
  for (const d of diff) {
    const k = `${d.sheet} · ${d.kind} · ${d.column}`;
    groups.set(k, [...(groups.get(k) ?? []), d]);
  }
  lines.push("## Summary", "", "| Sheet · kind · column | Count |", "| --- | --- |");
  for (const [k, v] of groups) lines.push(`| ${cell(k)} | ${v.length} |`);
  lines.push("");
  for (const [k, v] of groups) {
    lines.push(
      `## ${k}`,
      "",
      "| Row | Key | Bible | Playbook | Note |",
      "| --- | --- | --- | --- | --- |",
    );
    for (const d of v)
      lines.push(
        `| ${d.row ?? ""} | ${cell(d.key)} | ${cell(d.bible)} | ${cell(d.playbook)} | ${cell(d.note)} |`,
      );
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

export function importReport(
  counts: readonly CountResult[],
  map: ColumnMap,
  realWorld: readonly RealWorldRow[],
  reference: readonly ReferenceDiff[],
  rowCounts: ReadonlyMap<string, number>,
): string {
  const totals = dispositionTotals(map);
  const lines = [
    "# Canon import report",
    "",
    "## Counts",
    "",
    "| Entity | Parsed | Expected | Bible states | Result |",
    "| --- | --- | --- | --- | --- |",
  ];
  for (const c of counts)
    lines.push(
      `| ${c.entity} | ${c.parsed} | ${c.expected} | ${c.stated ?? ""} | ${c.ok ? "ok" : "FAIL"} |`,
    );
  lines.push("", "## Seeded rows", "", "| Table | Rows |", "| --- | --- |");
  for (const [t, n] of [...rowCounts].sort()) lines.push(`| xpms.${t} | ${n} |`);
  lines.push(
    "",
    "## Column map",
    "",
    `field ${totals.field}, computed ${totals.computed}, presentation ${totals.presentation}.`,
    "",
    "## Reference model check",
    "",
    "Importer output against design/xos-design-system/export/canon/0101_xpms_canon_seed.sql.",
    "",
    "| Table | Result |",
    "| --- | --- |",
  );
  for (const r of reference) {
    const ok = r.missing.length === 0 && r.extra.length === 0;
    lines.push(
      `| ${r.table} | ${ok ? "identical" : `${r.missing.length} missing, ${r.extra.length} extra`} |`,
    );
  }
  lines.push(
    "",
    "## Real-world rows",
    "",
    "Production Template rows naming real people, companies, contacts, venues or prices. The template stays private to the owner's org until the owner approves publishing it (Section 19.8).",
    "",
    "| Sheet | Row | ID | Columns |",
    "| --- | --- | --- | --- |",
  );
  for (const r of realWorld)
    lines.push(`| ${r.sheet} | ${r.row} | ${cell(r.id)} | ${cell(r.columns.join("; "))} |`);
  return `${lines.join("\n")}\n`;
}
