import { describe, expect, it } from "vitest";
import type * as Ref from "../src/types/reference";
import * as Ui from "../src/index.ts";

/**
 * Type test against the frozen prop contracts (design handoff gate 9). `tsc --noEmit` checks it:
 * each production prop type must accept every reference usage (the reference props are assignable
 * to it) and keep the reference shape (it is assignable to the reference props), and each component
 * must be usable where the reference component is declared.
 */
type Same<Prod, Reference> = [Reference] extends [Prod]
  ? [Prod] extends [Reference]
    ? true
    : false
  : false;
type Assert<T extends true> = T;
type Component<P> = (props: P) => unknown;
type Fits<C, Reference> = C extends Component<Reference> ? true : false;

export type PropContracts = [
  Assert<Same<Ui.ButtonProps, Ref.ButtonProps>>,
  Assert<Same<Ui.IconButtonProps, Ref.IconButtonProps>>,
  Assert<Same<Ui.KbdProps, Ref.KbdProps>>,
  Assert<Same<Ui.LinkProps, Ref.LinkProps>>,
  Assert<Same<Ui.IconProps, Ref.IconProps>>,
  Assert<Same<Ui.StateIconProps, Ref.StateIconProps>>,
  Assert<Same<Ui.DepartmentGlyphProps, Ref.DepartmentGlyphProps>>,
  Assert<Same<Ui.PhaseGlyphProps, Ref.PhaseGlyphProps>>,
  Assert<Same<Ui.RecordKindGlyphProps, Ref.RecordKindGlyphProps>>,
  Assert<Same<Ui.StateChipProps, Ref.StateChipProps>>,
  Assert<Same<Ui.PhaseChipProps, Ref.PhaseChipProps>>,
  Assert<Same<Ui.DepartmentChipProps, Ref.DepartmentChipProps>>,
  Assert<Same<Ui.URIDChipProps, Ref.URIDChipProps>>,
  Assert<Same<Ui.RecordKindChipProps, Ref.RecordKindChipProps>>,
  Assert<Same<Ui.PropertyChipProps, Ref.PropertyChipProps>>,
  Assert<Same<Ui.TagProps, Ref.TagProps>>,
  Assert<Same<Ui.BadgeProps, Ref.BadgeProps>>,
  Assert<Same<Ui.AvatarProps, Ref.AvatarProps>>,
  Assert<Same<Ui.AvatarStackProps, Ref.AvatarStackProps>>,
  Assert<Same<Ui.MoneyProps, Ref.MoneyProps>>,
  Assert<Same<Ui.InputProps, Ref.InputProps>>,
  Assert<Same<Ui.TextareaProps, Ref.TextareaProps>>,
  Assert<Same<Ui.CheckboxProps, Ref.CheckboxProps>>,
  Assert<Same<Ui.RadioProps, Ref.RadioProps>>,
  Assert<Same<Ui.SwitchProps, Ref.SwitchProps>>,
  Assert<Same<Ui.SelectProps, Ref.SelectProps>>,
  Assert<Same<Ui.NumberInputProps, Ref.NumberInputProps>>,
  Assert<Same<Ui.CurrencyInputProps, Ref.CurrencyInputProps>>,
  Assert<Same<Ui.DividerProps, Ref.DividerProps>>,
  Assert<Same<Ui.CardProps, Ref.CardProps>>,
  Assert<Same<Ui.SkeletonProps, Ref.SkeletonProps>>,
  Assert<Same<Ui.EmptyStateProps, Ref.EmptyStateProps>>,
  Assert<Same<Ui.ErrorStateProps, Ref.ErrorStateProps>>,
  Assert<Same<Ui.RefusalNoticeProps, Ref.RefusalNoticeProps>>,
  Assert<Same<Ui.InlineAlertProps, Ref.InlineAlertProps>>,
  Assert<Same<Ui.BannerProps, Ref.BannerProps>>,
  Assert<Same<Ui.ToastProps, Ref.ToastProps>>,
  Assert<Same<Ui.UndoToastProps, Ref.UndoToastProps>>,
  Assert<Same<Ui.DialogProps, Ref.DialogProps>>,
  Assert<Same<Ui.DrawerProps, Ref.DrawerProps>>,
  Assert<Same<Ui.SidePeekProps, Ref.SidePeekProps>>,
  Assert<Same<Ui.ShortcutSheetProps, Ref.ShortcutSheetProps>>,
  Assert<Same<Ui.PopoverProps, Ref.PopoverProps>>,
  Assert<Same<Ui.HoverCardProps, Ref.HoverCardProps>>,
  Assert<Same<Ui.TooltipProps, Ref.TooltipProps>>,
  Assert<Same<Ui.DropdownMenuProps, Ref.DropdownMenuProps>>,
  Assert<Same<Ui.ContextMenuProps, Ref.ContextMenuProps>>,
  Assert<Same<Ui.OrgSwitcherProps, Ref.OrgSwitcherProps>>,
  Assert<Same<Ui.CommandMenuProps, Ref.CommandMenuProps>>,
  Assert<Same<Ui.TabsProps, Ref.TabsProps>>,
  Assert<Same<Ui.SegmentedControlProps, Ref.SegmentedControlProps>>,
  Assert<Same<Ui.AccordionProps, Ref.AccordionProps>>,
  Assert<Same<Ui.BreadcrumbsProps, Ref.BreadcrumbsProps>>,
  Assert<Same<Ui.PaginationProps, Ref.PaginationProps>>,
  Assert<Same<Ui.SidebarProps, Ref.SidebarProps>>,
  Assert<Same<Ui.TopNavProps, Ref.TopNavProps>>,
  Assert<Same<Ui.TabBarProps, Ref.TabBarProps>>,
  Assert<Same<Ui.BrandMarkProps, Ref.BrandMarkProps>>,
  Assert<Same<Ui.AppShellProps, Ref.AppShellProps>>,
  Assert<Same<Ui.PageHeaderProps, Ref.PageHeaderProps>>,
  Assert<Same<Ui.ResizablePanelProps, Ref.ResizablePanelProps>>,
  Assert<Same<Ui.ScrollRegionProps, Ref.ScrollRegionProps>>,
  Assert<Same<Ui.StepperProps, Ref.StepperProps>>,
  Assert<Same<Ui.SplitViewProps, Ref.SplitViewProps>>,
  Assert<Same<Ui.DataTableProps, Ref.DataTableProps>>,
  Assert<Same<Ui.RecordRowProps, Ref.RecordRowProps>>,
  Assert<Same<Ui.RecordListProps, Ref.RecordListProps>>,
  Assert<Same<Ui.BoardProps, Ref.BoardProps>>,
  Assert<Same<Ui.TreeViewProps, Ref.TreeViewProps>>,
  Assert<Same<Ui.BulkActionBarProps, Ref.BulkActionBarProps>>,
  Assert<Same<Ui.ActivityFeedItemProps, Ref.ActivityFeedItemProps>>,
  Assert<Same<Ui.StatTileProps, Ref.StatTileProps>>,
  Assert<Same<Ui.GateReadinessPanelProps, Ref.GateReadinessPanelProps>>,
  Assert<Same<Ui.ProvenanceBadgeProps, Ref.ProvenanceBadgeProps>>,
  Assert<Same<Ui.AssertionRankBadgeProps, Ref.AssertionRankBadgeProps>>,
  Assert<Same<Ui.StalenessIndicatorProps, Ref.StalenessIndicatorProps>>,
  Assert<Same<Ui.ReconciliationTableProps, Ref.ReconciliationTableProps>>,
  Assert<Same<Ui.EmergencyCodeCardProps, Ref.EmergencyCodeCardProps>>,
  Assert<Same<Ui.RadioChannelTableProps, Ref.RadioChannelTableProps>>,
  Assert<Same<Ui.RunOfShowLiveProps, Ref.RunOfShowLiveProps>>,
  Assert<Same<Ui.CoordinateMatrixProps, Ref.CoordinateMatrixProps>>,
  Assert<Same<Ui.AccessGridMatrixProps, Ref.AccessGridMatrixProps>>,
  Assert<Same<Ui.ProgressBarProps, Ref.ProgressBarProps>>,
  Assert<Same<Ui.OpportunityCardProps, Ref.OpportunityCardProps>>,
  Assert<Same<Ui.OpportunityFiltersProps, Ref.OpportunityFiltersProps>>,
  Assert<Same<Ui.ApplicationFormProps, Ref.ApplicationFormProps>>,
  Assert<Same<Ui.AgencySlateProps, Ref.AgencySlateProps>>,
  Assert<Same<Ui.ProfileEditorProps, Ref.ProfileEditorProps>>,
  Assert<Same<Ui.EPKViewerProps, Ref.EPKViewerProps>>,
  Assert<Same<Ui.AvailabilityCalendarProps, Ref.AvailabilityCalendarProps>>,
  Assert<Same<Ui.OnboardingPacketProps, Ref.OnboardingPacketProps>>,
  Assert<Same<Ui.EngagementTimelineProps, Ref.EngagementTimelineProps>>,
  Assert<Same<Ui.RatingDialogProps, Ref.RatingDialogProps>>,
  Assert<Same<Ui.PayoutDetailsFormProps, Ref.PayoutDetailsFormProps>>,
  Assert<Same<Ui.PaymentTrackerProps, Ref.PaymentTrackerProps>>,
  Assert<Same<Ui.UpNextCardProps, Ref.UpNextCardProps>>,
];

export type ComponentContracts = [
  Assert<Fits<typeof Ui.Button, Ref.ButtonProps>>,
  Assert<Fits<typeof Ui.IconButton, Ref.IconButtonProps>>,
  Assert<Fits<typeof Ui.Kbd, Ref.KbdProps>>,
  Assert<Fits<typeof Ui.Link, Ref.LinkProps>>,
  Assert<Fits<typeof Ui.Icon, Ref.IconProps>>,
  Assert<Fits<typeof Ui.StateIcon, Ref.StateIconProps>>,
  Assert<Fits<typeof Ui.DepartmentGlyph, Ref.DepartmentGlyphProps>>,
  Assert<Fits<typeof Ui.PhaseGlyph, Ref.PhaseGlyphProps>>,
  Assert<Fits<typeof Ui.RecordKindGlyph, Ref.RecordKindGlyphProps>>,
  Assert<Fits<typeof Ui.StateChip, Ref.StateChipProps>>,
  Assert<Fits<typeof Ui.PhaseChip, Ref.PhaseChipProps>>,
  Assert<Fits<typeof Ui.DepartmentChip, Ref.DepartmentChipProps>>,
  Assert<Fits<typeof Ui.URIDChip, Ref.URIDChipProps>>,
  Assert<Fits<typeof Ui.RecordKindChip, Ref.RecordKindChipProps>>,
  Assert<Fits<typeof Ui.PropertyChip, Ref.PropertyChipProps>>,
  Assert<Fits<typeof Ui.Tag, Ref.TagProps>>,
  Assert<Fits<typeof Ui.Badge, Ref.BadgeProps>>,
  Assert<Fits<typeof Ui.Avatar, Ref.AvatarProps>>,
  Assert<Fits<typeof Ui.AvatarStack, Ref.AvatarStackProps>>,
  Assert<Fits<typeof Ui.Money, Ref.MoneyProps>>,
  Assert<Fits<typeof Ui.Input, Ref.InputProps>>,
  Assert<Fits<typeof Ui.Textarea, Ref.TextareaProps>>,
  Assert<Fits<typeof Ui.Checkbox, Ref.CheckboxProps>>,
  Assert<Fits<typeof Ui.Radio, Ref.RadioProps>>,
  Assert<Fits<typeof Ui.Switch, Ref.SwitchProps>>,
  Assert<Fits<typeof Ui.Select, Ref.SelectProps>>,
  Assert<Fits<typeof Ui.NumberInput, Ref.NumberInputProps>>,
  Assert<Fits<typeof Ui.CurrencyInput, Ref.CurrencyInputProps>>,
  Assert<Fits<typeof Ui.Divider, Ref.DividerProps>>,
  Assert<Fits<typeof Ui.Card, Ref.CardProps>>,
  Assert<Fits<typeof Ui.Skeleton, Ref.SkeletonProps>>,
  Assert<Fits<typeof Ui.EmptyState, Ref.EmptyStateProps>>,
  Assert<Fits<typeof Ui.ErrorState, Ref.ErrorStateProps>>,
  Assert<Fits<typeof Ui.RefusalNotice, Ref.RefusalNoticeProps>>,
  Assert<Fits<typeof Ui.InlineAlert, Ref.InlineAlertProps>>,
  Assert<Fits<typeof Ui.Banner, Ref.BannerProps>>,
  Assert<Fits<typeof Ui.Toast, Ref.ToastProps>>,
  Assert<Fits<typeof Ui.UndoToast, Ref.UndoToastProps>>,
  Assert<Fits<typeof Ui.Dialog, Ref.DialogProps>>,
  Assert<Fits<typeof Ui.Drawer, Ref.DrawerProps>>,
  Assert<Fits<typeof Ui.SidePeek, Ref.SidePeekProps>>,
  Assert<Fits<typeof Ui.ShortcutSheet, Ref.ShortcutSheetProps>>,
  Assert<Fits<typeof Ui.Popover, Ref.PopoverProps>>,
  Assert<Fits<typeof Ui.HoverCard, Ref.HoverCardProps>>,
  Assert<Fits<typeof Ui.Tooltip, Ref.TooltipProps>>,
  Assert<Fits<typeof Ui.DropdownMenu, Ref.DropdownMenuProps>>,
  Assert<Fits<typeof Ui.ContextMenu, Ref.ContextMenuProps>>,
  Assert<Fits<typeof Ui.OrgSwitcher, Ref.OrgSwitcherProps>>,
  Assert<Fits<typeof Ui.CommandMenu, Ref.CommandMenuProps>>,
  Assert<Fits<typeof Ui.Tabs, Ref.TabsProps>>,
  Assert<Fits<typeof Ui.SegmentedControl, Ref.SegmentedControlProps>>,
  Assert<Fits<typeof Ui.Accordion, Ref.AccordionProps>>,
  Assert<Fits<typeof Ui.Breadcrumbs, Ref.BreadcrumbsProps>>,
  Assert<Fits<typeof Ui.Pagination, Ref.PaginationProps>>,
  Assert<Fits<typeof Ui.Sidebar, Ref.SidebarProps>>,
  Assert<Fits<typeof Ui.TopNav, Ref.TopNavProps>>,
  Assert<Fits<typeof Ui.TabBar, Ref.TabBarProps>>,
  Assert<Fits<typeof Ui.BrandMark, Ref.BrandMarkProps>>,
  Assert<Fits<typeof Ui.AppShell, Ref.AppShellProps>>,
  Assert<Fits<typeof Ui.PageHeader, Ref.PageHeaderProps>>,
  Assert<Fits<typeof Ui.ResizablePanel, Ref.ResizablePanelProps>>,
  Assert<Fits<typeof Ui.ScrollRegion, Ref.ScrollRegionProps>>,
  Assert<Fits<typeof Ui.Stepper, Ref.StepperProps>>,
  Assert<Fits<typeof Ui.SplitView, Ref.SplitViewProps>>,
  Assert<Fits<typeof Ui.DataTable, Ref.DataTableProps>>,
  Assert<Fits<typeof Ui.RecordRow, Ref.RecordRowProps>>,
  Assert<Fits<typeof Ui.RecordList, Ref.RecordListProps>>,
  Assert<Fits<typeof Ui.Board, Ref.BoardProps>>,
  Assert<Fits<typeof Ui.TreeView, Ref.TreeViewProps>>,
  Assert<Fits<typeof Ui.BulkActionBar, Ref.BulkActionBarProps>>,
  Assert<Fits<typeof Ui.ActivityFeedItem, Ref.ActivityFeedItemProps>>,
  Assert<Fits<typeof Ui.StatTile, Ref.StatTileProps>>,
  Assert<Fits<typeof Ui.GateReadinessPanel, Ref.GateReadinessPanelProps>>,
  Assert<Fits<typeof Ui.ProvenanceBadge, Ref.ProvenanceBadgeProps>>,
  Assert<Fits<typeof Ui.AssertionRankBadge, Ref.AssertionRankBadgeProps>>,
  Assert<Fits<typeof Ui.StalenessIndicator, Ref.StalenessIndicatorProps>>,
  Assert<Fits<typeof Ui.ReconciliationTable, Ref.ReconciliationTableProps>>,
  Assert<Fits<typeof Ui.EmergencyCodeCard, Ref.EmergencyCodeCardProps>>,
  Assert<Fits<typeof Ui.RadioChannelTable, Ref.RadioChannelTableProps>>,
  Assert<Fits<typeof Ui.RunOfShowLive, Ref.RunOfShowLiveProps>>,
  Assert<Fits<typeof Ui.CoordinateMatrix, Ref.CoordinateMatrixProps>>,
  Assert<Fits<typeof Ui.AccessGridMatrix, Ref.AccessGridMatrixProps>>,
  Assert<Fits<typeof Ui.ProgressBar, Ref.ProgressBarProps>>,
  Assert<Fits<typeof Ui.OpportunityCard, Ref.OpportunityCardProps>>,
  Assert<Fits<typeof Ui.OpportunityFilters, Ref.OpportunityFiltersProps>>,
  Assert<Fits<typeof Ui.ApplicationForm, Ref.ApplicationFormProps>>,
  Assert<Fits<typeof Ui.AgencySlate, Ref.AgencySlateProps>>,
  Assert<Fits<typeof Ui.ProfileEditor, Ref.ProfileEditorProps>>,
  Assert<Fits<typeof Ui.EPKViewer, Ref.EPKViewerProps>>,
  Assert<Fits<typeof Ui.AvailabilityCalendar, Ref.AvailabilityCalendarProps>>,
  Assert<Fits<typeof Ui.OnboardingPacket, Ref.OnboardingPacketProps>>,
  Assert<Fits<typeof Ui.EngagementTimeline, Ref.EngagementTimelineProps>>,
  Assert<Fits<typeof Ui.RatingDialog, Ref.RatingDialogProps>>,
  Assert<Fits<typeof Ui.PayoutDetailsForm, Ref.PayoutDetailsFormProps>>,
  Assert<Fits<typeof Ui.PaymentTracker, Ref.PaymentTrackerProps>>,
  Assert<Fits<typeof Ui.UpNextCard, Ref.UpNextCardProps>>,
];

describe("reference contracts", () => {
  it("exports every component the contract test covers", () => {
    const names = [
      "Button",
      "IconButton",
      "Kbd",
      "Link",
      "Icon",
      "StateIcon",
      "DepartmentGlyph",
      "PhaseGlyph",
      "RecordKindGlyph",
      "StateChip",
      "PhaseChip",
      "DepartmentChip",
      "URIDChip",
      "RecordKindChip",
      "PropertyChip",
      "Tag",
      "Badge",
      "Avatar",
      "AvatarStack",
      "Money",
      "Input",
      "Textarea",
      "Checkbox",
      "Radio",
      "Switch",
      "Select",
      "NumberInput",
      "CurrencyInput",
      "Divider",
      "Card",
      "Skeleton",
      "EmptyState",
      "ErrorState",
      "RefusalNotice",
      "InlineAlert",
      "Banner",
      "Toast",
      "UndoToast",
      "Dialog",
      "Drawer",
      "SidePeek",
      "ShortcutSheet",
      "Popover",
      "HoverCard",
      "Tooltip",
      "DropdownMenu",
      "ContextMenu",
      "OrgSwitcher",
      "CommandMenu",
      "Tabs",
      "SegmentedControl",
      "Accordion",
      "Breadcrumbs",
      "Pagination",
      "Sidebar",
      "TopNav",
      "TabBar",
      "BrandMark",
      "AppShell",
      "PageHeader",
      "ResizablePanel",
      "ScrollRegion",
      "Stepper",
      "SplitView",
      "DataTable",
      "RecordRow",
      "RecordList",
      "Board",
      "TreeView",
      "BulkActionBar",
      "ActivityFeedItem",
      "StatTile",
      "GateReadinessPanel",
      "ProvenanceBadge",
      "AssertionRankBadge",
      "StalenessIndicator",
      "ReconciliationTable",
      "EmergencyCodeCard",
      "RadioChannelTable",
      "RunOfShowLive",
      "CoordinateMatrix",
      "AccessGridMatrix",
      "ProgressBar",
      "OpportunityCard",
      "OpportunityFilters",
      "ApplicationForm",
      "AgencySlate",
      "ProfileEditor",
      "EPKViewer",
      "AvailabilityCalendar",
      "OnboardingPacket",
      "EngagementTimeline",
      "RatingDialog",
      "PayoutDetailsForm",
      "PaymentTracker",
      "UpNextCard",
    ];
    const exported = Ui as unknown as Record<string, unknown>;
    expect(names.filter((n) => typeof exported[n] !== "function")).toEqual([]);
  });

  it("keeps the glyph map equal to the reference assignment", () => {
    expect(Ui.glyphs.departments["4000"]).toBe("Tent");
    expect(Ui.glyphs.phases.BLD).toBe("Hammer");
    expect(Ui.glyphs.recordKinds.Task).toBe("SquareCheck");
  });
});
