-- 0101_xpms_tables.sql
-- Generated by @xos/canon-import from canon/source. Do not edit by hand: change the canon
-- files or the importer and run `pnpm --filter @xos/canon-import canon:generate`.
-- Canon dimensions, catalog, bridges, the owner's reference model tables (decisions D11 to D17, D19) and governance (Section 7.2), with a comment on every table and column.

create table xpms.dim_department (
  dept_code xpms.canon_code not null check (dept_code ~ '^[0-9]000$'),
  department xpms.canon_text not null,
  source xpms.canon_text not null,
  note xpms.canon_text,
  executive_lead xpms.canon_text,
  core_function xpms.canon_text,
  scope xpms.canon_text,
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (dept_code)
);
comment on table xpms.dim_department is 'The ten locked department classes (Bible tab 01, Section 3.2), listed in numeric order. 4000 is Environment.';
comment on column xpms.dim_department.dept_code is 'Four-digit class code, 0000 to 9000.';
comment on column xpms.dim_department.department is 'Department label in Title Case.';
comment on column xpms.dim_department.source is 'Where the class comes from in canon (canon).';
comment on column xpms.dim_department.note is 'Bible note, such as the 4.0 label correction for 4000.';
comment on column xpms.dim_department.executive_lead is 'EXECUTIVE LEAD from the Playbook Departments sheet.';
comment on column xpms.dim_department.core_function is 'CORE FUNCTION from the Playbook Departments sheet.';
comment on column xpms.dim_department.scope is 'SCOPE from the Playbook Departments sheet.';
comment on column xpms.dim_department.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.dim_department.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.dim_department.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.dim_department.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.dim_department.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';

create table xpms.dim_discipline (
  disc_code xpms.canon_code not null check (disc_code ~ '^[0-9]{4}\.[0-9]{2}$'),
  dept_code xpms.canon_code not null references xpms.dim_department(dept_code),
  discipline xpms.canon_text not null,
  source xpms.canon_text not null,
  is_extension boolean generated always as (substr(disc_code, 6, 2)::integer >= 50) stored not null,
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (disc_code),
  check (left(disc_code, 4) = dept_code)
);
comment on table xpms.dim_discipline is 'Disciplines (Bible tab 02): canon codes .01 to .49 and adopter extensions .50 to .99 within a department.';
comment on column xpms.dim_discipline.disc_code is 'Discipline code DDDD.DD.';
comment on column xpms.dim_discipline.dept_code is 'Department class the discipline belongs to.';
comment on column xpms.dim_discipline.discipline is 'Discipline label in Title Case.';
comment on column xpms.dim_discipline.source is 'Origin of the discipline: canon, workforce, ramp-up or another tagged extension source.';
comment on column xpms.dim_discipline.is_extension is 'True when the discipline segment is .50 to .99 (an extension range).';
comment on column xpms.dim_discipline.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.dim_discipline.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.dim_discipline.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.dim_discipline.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.dim_discipline.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
create index dim_discipline_dept_code_idx on xpms.dim_discipline (dept_code);

create table xpms.dim_category (
  cat_urid xpms.canon_code not null check (cat_urid ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'),
  disc_code xpms.canon_code not null references xpms.dim_discipline(disc_code),
  category xpms.canon_text not null,
  source xpms.canon_text not null,
  xyz xpms.xyz_tag,
  is_extension boolean generated always as (substr(cat_urid, 6, 2)::integer >= 50 or substr(cat_urid, 9, 2)::integer >= 50) stored not null,
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (cat_urid),
  check (left(cat_urid, 7) = disc_code)
);
comment on table xpms.dim_category is 'Categories (Bible tab 03). The category URID DDDD.DD.DD is the universal semantic key; there is no fourth segment.';
comment on column xpms.dim_category.cat_urid is 'Category URID DDDD.DD.DD.';
comment on column xpms.dim_category.disc_code is 'Discipline the category belongs to.';
comment on column xpms.dim_category.category is 'Category label in Title Case.';
comment on column xpms.dim_category.source is 'Origin of the category: canon or a tagged extension source.';
comment on column xpms.dim_category.xyz is 'SCHEMA FAMILY (XYZ) from the Playbook Categories & URID Master sheet: X Resource, Y Process, Z Timeline.';
comment on column xpms.dim_category.is_extension is 'True when the discipline or category segment is .50 to .99.';
comment on column xpms.dim_category.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.dim_category.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.dim_category.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.dim_category.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.dim_category.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
create index dim_category_disc_code_idx on xpms.dim_category (disc_code);

create table xpms.dim_act (
  act_code xpms.canon_code not null,
  ordinal integer not null check (ordinal between 1 and 3),
  definition xpms.canon_text not null,
  primary key (act_code),
  unique (ordinal)
);
comment on table xpms.dim_act is 'The three acts PLAN, BUILD and SHOW (Bible tab 04). Acts group phases for presentation only; gates are the only control points.';
comment on column xpms.dim_act.act_code is 'Act code in capitals.';
comment on column xpms.dim_act.ordinal is 'Act order, 1 to 3.';
comment on column xpms.dim_act.definition is 'What the act covers, in sentence case.';

create table xpms.dim_phase (
  phase_code xpms.canon_code not null check (phase_code ~ '^[A-Z]{3}$'),
  gate integer not null check (gate between 1 and 9),
  phase xpms.canon_text not null,
  act_code xpms.canon_code not null references xpms.dim_act(act_code),
  definition xpms.canon_text not null,
  gate_exit xpms.canon_text not null,
  is_redefined boolean not null,
  primary key (phase_code),
  unique (gate),
  unique (phase)
);
comment on table xpms.dim_phase is 'The nine gated phases with fixed, append-only ordinals (Bible tab 05, Section 3.4). Gates 1 to 3 are Scope, Engage and Advance.';
comment on column xpms.dim_phase.phase_code is 'Three-letter phase code.';
comment on column xpms.dim_phase.gate is 'Gate ordinal, 1 to 9.';
comment on column xpms.dim_phase.phase is 'Phase label in Title Case.';
comment on column xpms.dim_phase.act_code is 'Act the phase is presented under.';
comment on column xpms.dim_phase.definition is 'What the phase covers.';
comment on column xpms.dim_phase.gate_exit is 'The condition that closes the gate.';
comment on column xpms.dim_phase.is_redefined is 'True when 4.0 kept the code but redefined the phase (Advance).';
create index dim_phase_act_code_idx on xpms.dim_phase (act_code);

create table xpms.dim_gate_criterion (
  criterion_id xpms.canon_code not null,
  gate integer not null references xpms.dim_phase(gate),
  ordinal integer not null check (ordinal > 0),
  statement xpms.canon_text not null,
  is_blocking boolean not null,
  primary key (criterion_id),
  unique (ordinal),
  check (criterion_id like 'G' || gate::text || '.%')
);
comment on table xpms.dim_gate_criterion is 'The 35 gate criteria (Bible tab 06). A blocking criterion stops the gate transition.';
comment on column xpms.dim_gate_criterion.criterion_id is 'Criterion code G{gate}.{NAME}.';
comment on column xpms.dim_gate_criterion.gate is 'Gate the criterion belongs to.';
comment on column xpms.dim_gate_criterion.ordinal is 'Position of the criterion in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_gate_criterion.statement is 'The criterion statement, sentence case.';
comment on column xpms.dim_gate_criterion.is_blocking is 'True when an unmet criterion stops the gate.';
create index dim_gate_criterion_gate_idx on xpms.dim_gate_criterion (gate);

create table xpms.dim_tier (
  tier_code xpms.canon_code not null check (tier_code ~ '^0[1-6]$'),
  tier xpms.canon_text not null,
  primary key (tier_code)
);
comment on table xpms.dim_tier is 'The six tiers of experience (Bible tab 07, Section 3.5). International is never a tier.';
comment on column xpms.dim_tier.tier_code is 'Two-digit tier code, 01 to 06.';
comment on column xpms.dim_tier.tier is 'Tier label.';

create table xpms.dim_team (
  team_id xpms.canon_code not null check (team_id ~ '^[0-9]{4}-T[0-9]{2}$'),
  team xpms.canon_text not null,
  dept_code xpms.canon_code not null references xpms.dim_department(dept_code),
  workgroup_tag xpms.canon_text,
  lead_role xpms.canon_text,
  responsibilities xpms.canon_text,
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (team_id),
  check (left(team_id, 4) = dept_code)
);
comment on table xpms.dim_team is 'Canon teams (Bible tab 08). A team is a tag that rolls up to a department, never a tree level.';
comment on column xpms.dim_team.team_id is 'Team code DDDD-Tnn.';
comment on column xpms.dim_team.team is 'Team label.';
comment on column xpms.dim_team.dept_code is 'Department the team rolls up to.';
comment on column xpms.dim_team.workgroup_tag is 'WORKGROUP TAG from the Playbook Teams sheet.';
comment on column xpms.dim_team.lead_role is 'LEAD ROLE from the Playbook Teams sheet.';
comment on column xpms.dim_team.responsibilities is 'RESPONSIBILITIES from the Playbook Teams sheet.';
comment on column xpms.dim_team.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.dim_team.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.dim_team.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.dim_team.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.dim_team.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
create index dim_team_dept_code_idx on xpms.dim_team (dept_code);

create table xpms.dim_tag (
  tag_id xpms.canon_code not null,
  tag_type xpms.canon_text not null,
  tag xpms.canon_text not null,
  primary key (tag_id)
);
comment on table xpms.dim_tag is 'Sustainability and compliance tags (Bible tab 09).';
comment on column xpms.dim_tag.tag_id is 'Tag code TAG-nnn.';
comment on column xpms.dim_tag.tag_type is 'Tag family, such as Sustainability or Compliance.';
comment on column xpms.dim_tag.tag is 'Tag value as written in canon.';

create table xpms.dim_assertion_rank (
  rank integer not null check (rank between 0 and 4),
  meaning xpms.canon_text not null,
  note xpms.canon_text,
  primary key (rank)
);
comment on table xpms.dim_assertion_rank is 'Assertion ranks 4 to 0 (Bible tab 22). Rank 0 is absent: not zero and not low.';
comment on column xpms.dim_assertion_rank.rank is 'Rank, 4 (attested) to 0 (absent).';
comment on column xpms.dim_assertion_rank.meaning is 'What a claim at this rank rests on.';
comment on column xpms.dim_assertion_rank.note is 'Canon examples for the rank.';

create table xpms.dim_assertion_word (
  domain xpms.canon_code not null check (domain in ('economics', 'compliance', 'capability')),
  word xpms.canon_code not null,
  rank integer not null references xpms.dim_assertion_rank(rank),
  primary key (domain, word),
  unique (domain, rank)
);
comment on table xpms.dim_assertion_word is 'Domain-native assertion words and their shared rank (Bible tab 22): economics, compliance and capability.';
comment on column xpms.dim_assertion_word.domain is 'Assertion domain.';
comment on column xpms.dim_assertion_word.word is 'Assertion word in capitals.';
comment on column xpms.dim_assertion_word.rank is 'Shared rank of the word.';
create index dim_assertion_word_rank_idx on xpms.dim_assertion_word (rank);

create table xpms.dim_provenance (
  provenance xpms.canon_code not null,
  rank integer not null check (rank > 0),
  definition xpms.canon_text not null,
  may_overwrite xpms.canon_text not null,
  max_confidence xpms.canon_code not null,
  primary key (provenance),
  unique (rank)
);
comment on table xpms.dim_provenance is 'Provenance ranks (Bible tab 19, Section 3.8): human 100, operator 80, imported 60, agent 40, provider 20.';
comment on column xpms.dim_provenance.provenance is 'Provenance name.';
comment on column xpms.dim_provenance.rank is 'Rank; a lower rank never overwrites a populated field written by a higher rank.';
comment on column xpms.dim_provenance.definition is 'Who writes with this provenance.';
comment on column xpms.dim_provenance.may_overwrite is 'What a writer of this provenance may overwrite, as canon states it.';
comment on column xpms.dim_provenance.max_confidence is 'Highest economics assertion word this provenance may carry.';

create table xpms.dim_staleness_policy (
  age_months_gte integer not null check (age_months_gte >= 0),
  action xpms.canon_code not null check (action in ('hold', 'degrade_one_step', 'degrade_to_modeled', 'expire')),
  detail xpms.canon_text,
  primary key (age_months_gte)
);
comment on table xpms.dim_staleness_policy is 'Staleness policy for price bands (Bible tab 14): degrade one step at 12 months, to MODELED at 24, expire at 36.';
comment on column xpms.dim_staleness_policy.age_months_gte is 'Band age in whole months from which the action applies.';
comment on column xpms.dim_staleness_policy.action is 'Action: hold, degrade_one_step, degrade_to_modeled or expire.';
comment on column xpms.dim_staleness_policy.detail is 'Canon detail for the action.';

create table xpms.jurisdiction (
  jurisdiction_id xpms.canon_code not null check (jurisdiction_id ~ '^[A-Z]{2}(-[A-Z0-9]+)*$'),
  ordinal integer not null check (ordinal > 0),
  level xpms.canon_code not null check (level in ('country', 'region', 'ahj')),
  country xpms.canon_code generated always as (left(jurisdiction_id, 2)) stored not null,
  parent xpms.canon_code references xpms.jurisdiction(jurisdiction_id),
  unit_system xpms.canon_code check (unit_system in ('imperial', 'metric')),
  currency xpms.currency_code,
  status xpms.canon_code not null check (status in ('populated', 'declared-unpopulated')),
  note xpms.canon_text,
  primary key (jurisdiction_id),
  unique (ordinal),
  check ((level = 'country') = (parent is null)),
  check (level <> 'country' or (unit_system is not null and currency is not null)),
  check (parent is null or left(parent, 2) = left(jurisdiction_id, 2))
);
comment on table xpms.jurisdiction is 'Jurisdictions (Bible tab 11) in third normal form (decision D19): the country derives from the ID; unit system and currency are stored on the country and inherited; code sets are rows of jurisdiction_code_set; jurisdiction_resolved returns tab 11 exactly. An unpopulated jurisdiction returns no answer; it never passes.';
comment on column xpms.jurisdiction.jurisdiction_id is 'Jurisdiction code, country first (US, US-FL, US-FL-MIAMI-DADE).';
comment on column xpms.jurisdiction.ordinal is 'Position of the jurisdiction in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.jurisdiction.level is 'country, region or ahj.';
comment on column xpms.jurisdiction.country is 'ISO 3166-1 alpha-2 country, derived from the ID.';
comment on column xpms.jurisdiction.parent is 'Enclosing jurisdiction; NULL for a country.';
comment on column xpms.jurisdiction.unit_system is 'imperial or metric; stated on the country and inherited unless a lower level states its own.';
comment on column xpms.jurisdiction.currency is 'ISO 4217 currency; stated on the country and inherited unless a lower level states its own.';
comment on column xpms.jurisdiction.status is 'populated or declared-unpopulated.';
comment on column xpms.jurisdiction.note is 'Canon note.';
create index jurisdiction_parent_idx on xpms.jurisdiction (parent);

create table xpms.dim_region (
  region_code xpms.canon_code not null,
  ordinal integer not null check (ordinal > 0),
  name xpms.canon_text not null,
  jurisdiction_id xpms.canon_code not null references xpms.jurisdiction(jurisdiction_id),
  currency_code xpms.currency_code not null,
  note xpms.canon_text,
  primary key (region_code)
);
comment on table xpms.dim_region is 'Cost regions (Bible tab 12). Only a region with a ratified multiplier prices; others refuse.';
comment on column xpms.dim_region.region_code is 'Region code.';
comment on column xpms.dim_region.ordinal is 'Position of the region in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_region.name is 'Region name.';
comment on column xpms.dim_region.jurisdiction_id is 'Jurisdiction the region resolves to.';
comment on column xpms.dim_region.currency_code is 'ISO 4217 currency of the region.';
comment on column xpms.dim_region.note is 'Canon note.';
create index dim_region_jurisdiction_id_idx on xpms.dim_region (jurisdiction_id);

create table xpms.dim_region_multiplier (
  region_code xpms.canon_code not null references xpms.dim_region(region_code),
  cost_multiplier numeric not null check (cost_multiplier > 0),
  is_basis boolean not null,
  primary key (region_code)
);
comment on table xpms.dim_region_multiplier is 'Ratified cost multipliers (Bible tab 12). A region without a row has no multiplier and refuses to price.';
comment on column xpms.dim_region_multiplier.region_code is 'Region the multiplier applies to.';
comment on column xpms.dim_region_multiplier.cost_multiplier is 'Multiplier applied to basis-region bands.';
comment on column xpms.dim_region_multiplier.is_basis is 'True for the basis region the bands were sourced in.';

create table xpms.dim_escalation_index (
  index_id xpms.canon_code not null,
  name xpms.canon_text not null,
  applies_to xpms.canon_code not null references xpms.jurisdiction(jurisdiction_id),
  note xpms.canon_text,
  primary key (index_id)
);
comment on table xpms.dim_escalation_index is 'Escalation indices (Bible tab 13) used to carry bands forward in time.';
comment on column xpms.dim_escalation_index.index_id is 'Index code.';
comment on column xpms.dim_escalation_index.name is 'Index name.';
comment on column xpms.dim_escalation_index.applies_to is 'Jurisdiction the index applies to.';
comment on column xpms.dim_escalation_index.note is 'Canon note.';
create index dim_escalation_index_applies_to_idx on xpms.dim_escalation_index (applies_to);

create table xpms.dim_permit_rule (
  rule xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  trigger_type xpms.canon_code not null,
  condition xpms.canon_text not null,
  permit xpms.canon_text not null,
  ahj xpms.canon_text not null,
  lead_time xpms.canon_text not null,
  jurisdiction_id xpms.canon_code not null references xpms.jurisdiction(jurisdiction_id),
  provenance xpms.canon_code not null references xpms.dim_provenance(provenance),
  note xpms.canon_text,
  primary key (rule),
  unique (ordinal)
);
comment on table xpms.dim_permit_rule is 'Permit rules (Bible tab 15), stamped to their jurisdiction.';
comment on column xpms.dim_permit_rule.rule is 'Rule name; unique within canon.';
comment on column xpms.dim_permit_rule.ordinal is 'Position of the rule in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_permit_rule.trigger_type is 'What triggers the rule: threshold, project, element or condition.';
comment on column xpms.dim_permit_rule.condition is 'Triggering condition.';
comment on column xpms.dim_permit_rule.permit is 'Permit or instrument required.';
comment on column xpms.dim_permit_rule.ahj is 'Authority having jurisdiction.';
comment on column xpms.dim_permit_rule.lead_time is 'Lead time as canon states it.';
comment on column xpms.dim_permit_rule.jurisdiction_id is 'Jurisdiction the rule binds to.';
comment on column xpms.dim_permit_rule.provenance is 'Provenance of the rule.';
comment on column xpms.dim_permit_rule.note is 'Canon note.';
create index dim_permit_rule_jurisdiction_id_idx on xpms.dim_permit_rule (jurisdiction_id);
create index dim_permit_rule_provenance_idx on xpms.dim_permit_rule (provenance);

create table xpms.dim_metric (
  domain xpms.canon_code not null,
  item xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  value_numeric numeric,
  value_text xpms.canon_text,
  qualifier xpms.canon_text,
  source xpms.canon_text,
  is_code_derived boolean not null,
  jurisdiction_id xpms.canon_code references xpms.jurisdiction(jurisdiction_id),
  is_jurisdiction_neutral boolean not null,
  provenance xpms.canon_code not null references xpms.dim_provenance(provenance),
  primary key (domain, item),
  unique (ordinal),
  check ((value_numeric is null) <> (value_text is null))
);
comment on table xpms.dim_metric is 'Code-derived and modeled metrics (Bible tab 16). A code-derived metric is bound to its jurisdiction.';
comment on column xpms.dim_metric.domain is 'Metric domain.';
comment on column xpms.dim_metric.item is 'What is measured.';
comment on column xpms.dim_metric.ordinal is 'Position of the metric in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_metric.value_numeric is 'Numeric value, when canon states a number.';
comment on column xpms.dim_metric.value_text is 'Value as text, when canon states it in words.';
comment on column xpms.dim_metric.qualifier is 'Qualifier of the value.';
comment on column xpms.dim_metric.source is 'Code section or basis of the value.';
comment on column xpms.dim_metric.is_code_derived is 'True when the value derives from an adopted code.';
comment on column xpms.dim_metric.jurisdiction_id is 'Jurisdiction a code-derived value binds to.';
comment on column xpms.dim_metric.is_jurisdiction_neutral is 'True when the value holds in any jurisdiction.';
comment on column xpms.dim_metric.provenance is 'Provenance of the metric.';
create index dim_metric_jurisdiction_id_idx on xpms.dim_metric (jurisdiction_id);
create index dim_metric_provenance_idx on xpms.dim_metric (provenance);

create table xpms.dim_identifier_class (
  class xpms.canon_code not null,
  ordinal integer not null check (ordinal > 0),
  issued_by xpms.canon_text not null,
  scope xpms.canon_text not null,
  is_mutable boolean not null,
  rule xpms.canon_text not null,
  examples xpms.canon_text not null,
  primary key (class)
);
comment on table xpms.dim_identifier_class is 'Identifier grammar (Bible tab 17): identifier, code and token. The tab 17 line banning status is superseded by Section 3.6 and is not enforced.';
comment on column xpms.dim_identifier_class.class is 'identifier, code or token.';
comment on column xpms.dim_identifier_class.ordinal is 'Position of the class in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_identifier_class.issued_by is 'Who issues values of the class.';
comment on column xpms.dim_identifier_class.scope is 'Scope within which a value is unique.';
comment on column xpms.dim_identifier_class.is_mutable is 'True when values may change under governance.';
comment on column xpms.dim_identifier_class.rule is 'The governing rule.';
comment on column xpms.dim_identifier_class.examples is 'Canon examples.';

create table xpms.dim_grain (
  grain xpms.canon_code not null,
  ordinal integer not null check (ordinal > 0),
  counts xpms.canon_text not null,
  identified_by xpms.canon_text not null,
  answers xpms.canon_text not null,
  note xpms.canon_text,
  primary key (grain)
);
comment on table xpms.dim_grain is 'Grain (Bible tab 18): class, unit and lot.';
comment on column xpms.dim_grain.grain is 'class, unit or lot.';
comment on column xpms.dim_grain.ordinal is 'Position of the grain in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_grain.counts is 'What the grain counts.';
comment on column xpms.dim_grain.identified_by is 'Identifiers of the grain.';
comment on column xpms.dim_grain.answers is 'The question the grain answers.';
comment on column xpms.dim_grain.note is 'Canon note.';

create table xpms.dim_facet (
  facet xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  form xpms.canon_text,
  rolls_up_to xpms.canon_text,
  since xpms.canon_text,
  note xpms.canon_text,
  primary key (facet)
);
comment on table xpms.dim_facet is 'Facets carried from canon (Bible tab 20).';
comment on column xpms.dim_facet.facet is 'Facet name.';
comment on column xpms.dim_facet.ordinal is 'Position of the facet in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_facet.form is 'How the facet is represented.';
comment on column xpms.dim_facet.rolls_up_to is 'Facet it rolls up to.';
comment on column xpms.dim_facet.since is 'Canon version that introduced the facet.';
comment on column xpms.dim_facet.note is 'Canon note.';

create table xpms.dim_identity_axis (
  axis xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  example xpms.canon_text not null,
  answers xpms.canon_text not null,
  name_class xpms.canon_code not null references xpms.dim_identifier_class(class),
  primary key (axis)
);
comment on table xpms.dim_identity_axis is 'Identity doctrine axes (Bible tab 21). The crosswalk GTIN to GPC brick to UNSPSC to URID is proposed and human-confirmed, never automatic.';
comment on column xpms.dim_identity_axis.axis is 'Identity axis.';
comment on column xpms.dim_identity_axis.ordinal is 'Position of the axis in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_identity_axis.example is 'Canon example value.';
comment on column xpms.dim_identity_axis.answers is 'The question the axis answers.';
comment on column xpms.dim_identity_axis.name_class is 'Identifier grammar class of the axis.';
create index dim_identity_axis_name_class_idx on xpms.dim_identity_axis (name_class);

create table xpms.dim_record_class (
  record_class xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  primary key (record_class),
  unique (ordinal)
);
comment on table xpms.dim_record_class is 'The five record classes (Bible tab 24): Work, Artifact, Commitment, Control and Time.';
comment on column xpms.dim_record_class.record_class is 'Record class.';
comment on column xpms.dim_record_class.ordinal is 'Order of first appearance in Bible tab 24.';

create table xpms.dim_record_kind (
  record_kind xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  definition xpms.canon_text not null,
  definition_of_done xpms.canon_text not null,
  record_class xpms.canon_text not null references xpms.dim_record_class(record_class),
  title_grammar xpms.canon_text not null,
  primary key (record_kind),
  unique (ordinal)
);
comment on table xpms.dim_record_kind is 'The 26 record kinds (Bible tab 24), each with a definition of done and a title grammar.';
comment on column xpms.dim_record_kind.record_kind is 'Record kind.';
comment on column xpms.dim_record_kind.ordinal is 'Position of the record kind in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_record_kind.definition is 'What a record of the kind is.';
comment on column xpms.dim_record_kind.definition_of_done is 'When a record of the kind is done.';
comment on column xpms.dim_record_kind.record_class is 'Class of the kind.';
comment on column xpms.dim_record_kind.title_grammar is 'Title grammar validated on write.';
create index dim_record_kind_record_class_idx on xpms.dim_record_kind (record_class);

create table xpms.dim_record_subtype (
  record_kind xpms.canon_text not null references xpms.dim_record_kind(record_kind),
  record_subtype xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  unspsc_segment xpms.canon_text,
  primary key (record_kind, record_subtype),
  unique (ordinal)
);
comment on table xpms.dim_record_subtype is 'The 124 kind-scoped record subtypes (Bible tab 25). The composite key lets a record carry a subtype only for its own kind.';
comment on column xpms.dim_record_subtype.record_kind is 'Kind the subtype belongs to.';
comment on column xpms.dim_record_subtype.record_subtype is 'Subtype label.';
comment on column xpms.dim_record_subtype.ordinal is 'Position of the subtype in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_record_subtype.unspsc_segment is 'UNSPSC segment and its title, where canon gives one.';

create table xpms.dim_record_state (
  record_state xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  meaning xpms.canon_text not null,
  primary key (record_state),
  unique (ordinal)
);
comment on table xpms.dim_record_state is 'The nine record states (Bible tab 26). Canceled, never Cancelled.';
comment on column xpms.dim_record_state.record_state is 'Record state.';
comment on column xpms.dim_record_state.ordinal is 'Position of the state in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_record_state.meaning is 'What the state means.';

create table xpms.dim_state (
  state xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  family xpms.canon_text not null,
  meaning xpms.canon_text not null,
  applies_to xpms.canon_text not null,
  primary key (state),
  unique (ordinal)
);
comment on table xpms.dim_state is 'The shared state vocabulary (Bible tab 37): five core states plus small domain extensions.';
comment on column xpms.dim_state.state is 'State label.';
comment on column xpms.dim_state.ordinal is 'Position of the state in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_state.family is 'Core or the domain extension the state belongs to.';
comment on column xpms.dim_state.meaning is 'What the state means.';
comment on column xpms.dim_state.applies_to is 'What the state applies to.';

create table xpms.dim_role (
  role_code xpms.canon_code not null check (role_code ~ '^[0-9]{4}\.[0-9]{2}\.[0-9]{2}$'),
  role xpms.canon_text not null,
  dept_code xpms.canon_code not null references xpms.dim_department(dept_code),
  staffing_ratio numeric,
  ratio_basis xpms.canon_text,
  kit_basis xpms.canon_text,
  job_title xpms.canon_text,
  primary key (role_code),
  check (left(role_code, 4) = dept_code)
);
comment on table xpms.dim_role is 'The 61 workforce roles (Bible tab 27) with function name, job title and staffing ratio. Role codes share the URID shape.';
comment on column xpms.dim_role.role_code is 'Role code DDDD.DD.DD.';
comment on column xpms.dim_role.role is 'Function name of the role.';
comment on column xpms.dim_role.dept_code is 'Department the role belongs to.';
comment on column xpms.dim_role.staffing_ratio is 'Staffing ratio, read with ratio_basis.';
comment on column xpms.dim_role.ratio_basis is 'Basis of the staffing ratio.';
comment on column xpms.dim_role.kit_basis is 'Kit or scheduling basis.';
comment on column xpms.dim_role.job_title is 'Job title, where canon names one.';
create index dim_role_dept_code_idx on xpms.dim_role (dept_code);

create table xpms.dim_gl_account_type (
  account_type xpms.canon_text not null,
  normal_balance xpms.canon_code check (normal_balance in ('Debit', 'Credit')),
  primary key (account_type)
);
comment on table xpms.dim_gl_account_type is 'General ledger account types and their normal balance (Playbook GL Accounts sheet, NORMAL BALANCE).';
comment on column xpms.dim_gl_account_type.account_type is 'Account type: Asset, Liability, Equity, Revenue or Expense.';
comment on column xpms.dim_gl_account_type.normal_balance is 'Debit or Credit.';

create table xpms.dim_gl_account (
  account_code xpms.canon_code not null check (account_code ~ '^[0-9]{2}00$'),
  account_name xpms.canon_text not null,
  account_type xpms.canon_text not null references xpms.dim_gl_account_type(account_type),
  tax_type xpms.canon_text not null,
  description xpms.canon_text not null,
  class_code xpms.canon_code generated always as (case when account_type in ('Revenue', 'Expense') then substr(account_code, 2, 1) || '000' end) stored references xpms.dim_department(dept_code),
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (account_code),
  unique (class_code, account_type)
);
comment on table xpms.dim_gl_account is 'The fixed 23-account chart (Bible tab 29 and the GL chart CSV). Tenants cannot add accounts.';
comment on column xpms.dim_gl_account.account_code is 'Four-digit account: ledger type digit, class digit, 00.';
comment on column xpms.dim_gl_account.account_name is 'Account name.';
comment on column xpms.dim_gl_account.account_type is 'Account type.';
comment on column xpms.dim_gl_account.tax_type is 'Default tax type: Tax on Purchases, Tax on Sales, Tax Exempt or None.';
comment on column xpms.dim_gl_account.description is 'What posts to the account.';
comment on column xpms.dim_gl_account.class_code is 'Department class of a revenue or expense account, derived from the class digit; NULL for balance sheet accounts (decision D13: postings resolve by class).';
comment on column xpms.dim_gl_account.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.dim_gl_account.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.dim_gl_account.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.dim_gl_account.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.dim_gl_account.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
create index dim_gl_account_account_type_idx on xpms.dim_gl_account (account_type);

create table xpms.dim_cost_center_template (
  cost_center_id xpms.canon_code not null,
  ordinal integer not null check (ordinal > 0),
  cost_center xpms.canon_text not null,
  kind xpms.canon_text not null,
  scope_code xpms.canon_code,
  note xpms.canon_text,
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (cost_center_id)
);
comment on table xpms.dim_cost_center_template is 'Cost center templates (Bible tab 30), dimension 1: standing operations, corporate overhead and one per event scope.';
comment on column xpms.dim_cost_center_template.cost_center_id is 'Cost center code.';
comment on column xpms.dim_cost_center_template.ordinal is 'Position of the cost center in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_cost_center_template.cost_center is 'Cost center name.';
comment on column xpms.dim_cost_center_template.kind is 'Standing, Overhead or Event.';
comment on column xpms.dim_cost_center_template.scope_code is 'Event scope code, for event cost centers.';
comment on column xpms.dim_cost_center_template.note is 'Canon note.';
comment on column xpms.dim_cost_center_template.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.dim_cost_center_template.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.dim_cost_center_template.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.dim_cost_center_template.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.dim_cost_center_template.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';

create table xpms.dim_counterparty_type (
  counterparty_type xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  definition xpms.canon_text not null,
  classification_code xpms.canon_code,
  vendor_class xpms.canon_text,
  clearance_tier xpms.canon_text,
  default_account_code xpms.canon_code references xpms.dim_gl_account(account_code),
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (counterparty_type),
  unique (classification_code)
);
comment on table xpms.dim_counterparty_type is 'The counterparty types (Bible tab 28). A vendor engagement carries a counterparty type; an internal one carries a role code.';
comment on column xpms.dim_counterparty_type.counterparty_type is 'Counterparty type.';
comment on column xpms.dim_counterparty_type.ordinal is 'Position of the counterparty type in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_counterparty_type.definition is 'What the counterparty does.';
comment on column xpms.dim_counterparty_type.classification_code is 'CLASSIFICATION CODE from the Playbook Counterparty Types sheet.';
comment on column xpms.dim_counterparty_type.vendor_class is 'VENDOR CLASS from the Playbook Counterparty Types sheet.';
comment on column xpms.dim_counterparty_type.clearance_tier is 'CLEARANCE TIER from the Playbook Counterparty Types sheet.';
comment on column xpms.dim_counterparty_type.default_account_code is 'DEFAULT GL ACCOUNT from the Playbook Counterparty Types sheet.';
comment on column xpms.dim_counterparty_type.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.dim_counterparty_type.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.dim_counterparty_type.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.dim_counterparty_type.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.dim_counterparty_type.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
create index dim_counterparty_type_default_account_code_idx on xpms.dim_counterparty_type (default_account_code);

create table xpms.dim_category_gl (
  cat_urid xpms.canon_code not null references xpms.dim_category(cat_urid),
  default_cost_center xpms.canon_code not null references xpms.dim_cost_center_template(cost_center_id),
  primary key (cat_urid)
);
comment on table xpms.dim_category_gl is 'Default cost center of each category (Bible tab 31). The GL account is derived by class (decision D13, view xpms.v_category_gl); the importer verifies tab 31 states the same account.';
comment on column xpms.dim_category_gl.cat_urid is 'Category.';
comment on column xpms.dim_category_gl.default_cost_center is 'Default dimension 1.';
create index dim_category_gl_default_cost_center_idx on xpms.dim_category_gl (default_cost_center);

create table xpms.dim_touchpoint (
  touchpoint_id xpms.canon_code not null,
  ordinal integer not null check (ordinal > 0),
  sense xpms.canon_text not null,
  brief_element xpms.canon_text not null,
  category xpms.canon_text not null,
  item xpms.canon_text not null,
  base xpms.canon_text not null,
  elevated xpms.canon_text not null,
  premium xpms.canon_text not null,
  optional_upgrades xpms.canon_text,
  add_ons xpms.canon_text,
  substitutions xpms.canon_text,
  venue_zone xpms.canon_text,
  event_tier_fit xpms.canon_text,
  dept_code xpms.canon_code not null references xpms.dim_department(dept_code),
  division xpms.canon_text,
  tier_code xpms.canon_code not null references xpms.dim_tier(tier_code),
  lifecycle_phase_code xpms.canon_code references xpms.dim_phase(phase_code),
  xyz xpms.xyz_tag not null,
  primary key (touchpoint_id)
);
comment on table xpms.dim_touchpoint is 'The 90 five-sense touchpoints (Bible tab 10) with Base, Elevated and Premium grades.';
comment on column xpms.dim_touchpoint.touchpoint_id is 'Touchpoint code.';
comment on column xpms.dim_touchpoint.ordinal is 'Position of the touchpoint in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_touchpoint.sense is 'Sense family.';
comment on column xpms.dim_touchpoint.brief_element is 'Brief element.';
comment on column xpms.dim_touchpoint.category is 'Touchpoint category.';
comment on column xpms.dim_touchpoint.item is 'Touchpoint item.';
comment on column xpms.dim_touchpoint.base is 'Base grade description.';
comment on column xpms.dim_touchpoint.elevated is 'Elevated grade description.';
comment on column xpms.dim_touchpoint.premium is 'Premium grade description.';
comment on column xpms.dim_touchpoint.optional_upgrades is 'Optional upgrades.';
comment on column xpms.dim_touchpoint.add_ons is 'Add-ons.';
comment on column xpms.dim_touchpoint.substitutions is 'Substitutions.';
comment on column xpms.dim_touchpoint.venue_zone is 'Venue zone.';
comment on column xpms.dim_touchpoint.event_tier_fit is 'Event tier fit as canon states it.';
comment on column xpms.dim_touchpoint.dept_code is 'Department class.';
comment on column xpms.dim_touchpoint.division is 'Division label.';
comment on column xpms.dim_touchpoint.tier_code is 'Tier of experience.';
comment on column xpms.dim_touchpoint.lifecycle_phase_code is 'Lifecycle gate, relabeled to 4.0; NULL where canon names a value that is not a gated phase (held in xpms.intake).';
comment on column xpms.dim_touchpoint.xyz is 'Schema family tag.';
create index dim_touchpoint_dept_code_idx on xpms.dim_touchpoint (dept_code);
create index dim_touchpoint_tier_code_idx on xpms.dim_touchpoint (tier_code);
create index dim_touchpoint_lifecycle_phase_code_idx on xpms.dim_touchpoint (lifecycle_phase_code);

create table xpms.dim_unit_dimension (
  dimension_code xpms.canon_code not null,
  name xpms.canon_text not null,
  primary key (dimension_code)
);
comment on table xpms.dim_unit_dimension is 'Physical dimensions of units (count, length, time and so on). Canon 4.0 states none; rows arrive through intake.';
comment on column xpms.dim_unit_dimension.dimension_code is 'Dimension code.';
comment on column xpms.dim_unit_dimension.name is 'Dimension name.';

create table xpms.dim_unit_alias (
  alias xpms.canon_text not null,
  unit_code xpms.canon_text not null,
  dimension_code xpms.canon_code references xpms.dim_unit_dimension(dimension_code),
  primary key (alias)
);
comment on table xpms.dim_unit_alias is 'Unit bases used by canon (the Item Catalog unit_basis values). A unit without a dimension refuses arithmetic rather than guessing.';
comment on column xpms.dim_unit_alias.alias is 'Unit basis as written in canon.';
comment on column xpms.dim_unit_alias.unit_code is 'Canonical unit the alias resolves to.';
comment on column xpms.dim_unit_alias.dimension_code is 'Dimension of the unit, once ratified.';
create index dim_unit_alias_dimension_code_idx on xpms.dim_unit_alias (dimension_code);

create table xpms.grade (
  code xpms.canon_code not null check (code in ('base', 'elevated', 'premium')),
  label xpms.canon_text not null,
  sort_order integer not null,
  primary key (code),
  unique (label),
  unique (sort_order)
);
comment on table xpms.grade is 'Price grades Base, Elevated and Premium (decision D11). Labels are data; the Bible tab 34 labels Grade 1 Basic, Grade 2 Standard and Grade 3 Premium are superseded.';
comment on column xpms.grade.code is 'base, elevated or premium.';
comment on column xpms.grade.label is 'Grade label.';
comment on column xpms.grade.sort_order is 'Display order.';

create table xpms.dim_upl_field (
  field xpms.canon_code not null,
  ordinal integer not null check (ordinal > 0),
  rule xpms.canon_text not null,
  primary key (field)
);
comment on table xpms.dim_upl_field is 'The Universal Posting Line (Bible tab 36): one export shape and its platform mappings.';
comment on column xpms.dim_upl_field.field is 'Field or platform name.';
comment on column xpms.dim_upl_field.ordinal is 'Position of the field in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_upl_field.rule is 'Rule or mapping for the field.';

create table xpms.dim_budget_template_rule (
  field xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  rule xpms.canon_text not null,
  primary key (field)
);
comment on table xpms.dim_budget_template_rule is 'The budget template specification (Bible tab 34).';
comment on column xpms.dim_budget_template_rule.field is 'Template field or topic.';
comment on column xpms.dim_budget_template_rule.ordinal is 'Position of the rule in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_budget_template_rule.rule is 'The rule.';

create table xpms.dim_change_record (
  change xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  from_value xpms.canon_text not null,
  to_value xpms.canon_text not null,
  why xpms.canon_text not null,
  primary key (change)
);
comment on table xpms.dim_change_record is 'The 3.0 to 4.0 change record (Bible tab 35). Codes never move.';
comment on column xpms.dim_change_record.change is 'What changed.';
comment on column xpms.dim_change_record.ordinal is 'Position of the change in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.dim_change_record.from_value is 'Value in 3.0.';
comment on column xpms.dim_change_record.to_value is 'Value in 4.0.';
comment on column xpms.dim_change_record.why is 'Reason for the change.';

create table xpms.canon_statement (
  tab xpms.canon_text not null,
  ordinal integer not null check (ordinal > 0),
  item xpms.canon_text,
  statement xpms.canon_text,
  primary key (tab, ordinal)
);
comment on table xpms.canon_statement is 'Narrative Bible rows that are statements rather than dimension members: the cover, the silence rule, identity doctrine notes and build provenance.';
comment on column xpms.canon_statement.tab is 'Bible tab the statement comes from.';
comment on column xpms.canon_statement.ordinal is 'Position of the statement in its Bible tab; the canonical display order where the code is not numeric.';
comment on column xpms.canon_statement.item is 'Statement heading.';
comment on column xpms.canon_statement.statement is 'Statement text.';

create table xpms.dim_urn_namespace (
  kind xpms.canon_code not null check (kind ~ '^[a-z][a-z_]*$'),
  table_name xpms.canon_code not null,
  key_column xpms.canon_code not null,
  label_column xpms.canon_code not null,
  primary key (kind)
);
comment on table xpms.dim_urn_namespace is 'URN kinds resolvable under urn:xpms (Section 3.1): urn:xpms:{kind}:{key}.';
comment on column xpms.dim_urn_namespace.kind is 'URN kind segment.';
comment on column xpms.dim_urn_namespace.table_name is 'xpms table holding the kind.';
comment on column xpms.dim_urn_namespace.key_column is 'Natural key column of that table.';
comment on column xpms.dim_urn_namespace.label_column is 'Column holding the display label.';

create table xpms.dim_locale (
  locale_code xpms.canon_code not null,
  name xpms.canon_text not null,
  is_source boolean not null,
  release_stage xpms.canon_code not null check (release_stage in ('general', 'beta')),
  primary key (locale_code)
);
comment on table xpms.dim_locale is 'Locales canon labels can be translated into (Section 15). Codes are never translated.';
comment on column xpms.dim_locale.locale_code is 'BCP 47 locale code.';
comment on column xpms.dim_locale.name is 'Locale name in English.';
comment on column xpms.dim_locale.is_source is 'True for the source locale, en-US.';
comment on column xpms.dim_locale.release_stage is 'general or beta.';

create table xpms.elements (
  element_id xpms.canon_code not null,
  urid xpms.canon_code not null references xpms.dim_category(cat_urid),
  item xpms.canon_text not null,
  common_name xpms.canon_text,
  kind xpms.canon_code not null,
  unit_basis xpms.canon_text not null references xpms.dim_unit_alias(alias),
  grade xpms.canon_text not null,
  description xpms.canon_text,
  specification xpms.canon_text,
  xyz xpms.xyz_tag not null,
  xyz_basis xpms.canon_text not null,
  tier_code xpms.canon_code not null references xpms.dim_tier(tier_code),
  lead_time_hours numeric,
  crew xpms.canon_text,
  unspsc xpms.canon_code,
  purchase_account xpms.canon_code references xpms.dim_gl_account(account_code),
  sales_account xpms.canon_code references xpms.dim_gl_account(account_code),
  default_cost_center xpms.canon_code not null references xpms.dim_cost_center_template(cost_center_id),
  price_evidence xpms.canon_text,
  source xpms.canon_text not null,
  mapping_confidence xpms.canon_text not null,
  lifecycle_state xpms.canon_text not null references xpms.dim_state(state),
  external_ref xpms.canon_text,
  source_row integer,
  primary key (element_id),
  check (left(element_id, 11) = urid || '-'),
  check (purchase_account is not null or sales_account is not null)
);
comment on table xpms.elements is 'The catalog: 1,211 elements (Bible tab 32 and the Item Catalog CSV). Item IDs follow {URID}-{ORG}-{SEQ}.';
comment on column xpms.elements.element_id is 'Item ID {URID}-{ORG}-{SEQ}.';
comment on column xpms.elements.urid is 'Category URID of the element.';
comment on column xpms.elements.item is 'Item name in Title Case.';
comment on column xpms.elements.common_name is 'Common name.';
comment on column xpms.elements.kind is 'Resource kind.';
comment on column xpms.elements.unit_basis is 'Unit basis.';
comment on column xpms.elements.grade is 'Experience grade of the element: Standard, Base, Elevated or Premium.';
comment on column xpms.elements.description is 'Description, sentence case.';
comment on column xpms.elements.specification is 'Specification.';
comment on column xpms.elements.xyz is 'Schema family tag.';
comment on column xpms.elements.xyz_basis is 'Basis of the XYZ tag, stored beside it.';
comment on column xpms.elements.tier_code is 'Tier of experience.';
comment on column xpms.elements.lead_time_hours is 'Lead time in hours.';
comment on column xpms.elements.crew is 'Crew needed.';
comment on column xpms.elements.unspsc is 'UNSPSC identifier; recorded, never minted.';
comment on column xpms.elements.purchase_account is 'Purchase account.';
comment on column xpms.elements.sales_account is 'Sales account.';
comment on column xpms.elements.default_cost_center is 'Default dimension 1.';
comment on column xpms.elements.price_evidence is 'Source of the price bands.';
comment on column xpms.elements.source is 'Where the element entered canon.';
comment on column xpms.elements.mapping_confidence is 'How the element was mapped to its URID.';
comment on column xpms.elements.lifecycle_state is 'Lifecycle state from the shared vocabulary.';
comment on column xpms.elements.external_ref is 'Legacy code or touchpoint ID; never a join key.';
comment on column xpms.elements.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
create index elements_urid_idx on xpms.elements (urid);
create index elements_unit_basis_idx on xpms.elements (unit_basis);
create index elements_tier_code_idx on xpms.elements (tier_code);
create index elements_purchase_account_idx on xpms.elements (purchase_account);
create index elements_sales_account_idx on xpms.elements (sales_account);
create index elements_default_cost_center_idx on xpms.elements (default_cost_center);
create index elements_lifecycle_state_idx on xpms.elements (lifecycle_state);

create table xpms.element_price_bands (
  element_id xpms.canon_code not null references xpms.elements(element_id),
  grade_code xpms.canon_code not null references xpms.grade(code),
  amount_minor bigint not null check (amount_minor >= 0),
  currency_code xpms.currency_code not null,
  assertion_word xpms.canon_code,
  valid_from date,
  valid_to date,
  primary key (element_id, grade_code),
  check (valid_to is null or valid_from is null or valid_to >= valid_from)
);
comment on table xpms.element_price_bands is 'Price bands per element and grade. NULL is never stored: an element without a band is unpriced.';
comment on column xpms.element_price_bands.element_id is 'Element priced.';
comment on column xpms.element_price_bands.grade_code is 'Price grade.';
comment on column xpms.element_price_bands.amount_minor is 'Amount in minor units of currency_code.';
comment on column xpms.element_price_bands.currency_code is 'ISO 4217 currency of the amount.';
comment on column xpms.element_price_bands.assertion_word is 'Economics assertion word; NULL means canon states none and confidence resolves as no answer.';
comment on column xpms.element_price_bands.valid_from is 'Date the band was sourced; NULL means canon states none.';
comment on column xpms.element_price_bands.valid_to is 'Date the band stops applying, if stated.';
create index element_price_bands_grade_code_idx on xpms.element_price_bands (grade_code);

create table xpms.element_gtins (
  gtin xpms.canon_code not null check (gtin ~ '^[0-9]{14}$'),
  element_id xpms.canon_code not null references xpms.elements(element_id),
  gpc_brick xpms.canon_code,
  confirmed_by xpms.canon_text not null,
  primary key (gtin)
);
comment on table xpms.element_gtins is 'GTINs bound to elements. Many GTINs map to one element; one GTIN maps to at most one element. Never one-to-one.';
comment on column xpms.element_gtins.gtin is 'GTIN-14 identifier.';
comment on column xpms.element_gtins.element_id is 'Element the trade item is an instance of.';
comment on column xpms.element_gtins.gpc_brick is 'GS1 GPC brick of the trade item.';
comment on column xpms.element_gtins.confirmed_by is 'Named human who confirmed the crosswalk; it is never automatic.';
create index element_gtins_element_id_idx on xpms.element_gtins (element_id);

create table xpms.bridge_element_phase (
  element_id xpms.canon_code not null references xpms.elements(element_id),
  phase_code xpms.canon_code not null references xpms.dim_phase(phase_code),
  is_default boolean not null,
  primary key (element_id, phase_code)
);
comment on table xpms.bridge_element_phase is 'Phase participation of an element, multi-valued (Section 3.4).';
comment on column xpms.bridge_element_phase.element_id is 'Element.';
comment on column xpms.bridge_element_phase.phase_code is 'Phase the element participates in.';
comment on column xpms.bridge_element_phase.is_default is 'True for the element''s default phase from the catalog.';
create index bridge_element_phase_phase_code_idx on xpms.bridge_element_phase (phase_code);

create table xpms.bridge_element_tag (
  element_id xpms.canon_code not null references xpms.elements(element_id),
  tag_id xpms.canon_code not null references xpms.dim_tag(tag_id),
  primary key (element_id, tag_id)
);
comment on table xpms.bridge_element_tag is 'Sustainability and compliance tags of an element.';
comment on column xpms.bridge_element_tag.element_id is 'Element.';
comment on column xpms.bridge_element_tag.tag_id is 'Tag.';
create index bridge_element_tag_tag_id_idx on xpms.bridge_element_tag (tag_id);

create table xpms.bridge_element_permit (
  element_id xpms.canon_code not null references xpms.elements(element_id),
  rule xpms.canon_text not null references xpms.dim_permit_rule(rule),
  primary key (element_id, rule)
);
comment on table xpms.bridge_element_permit is 'Permit rules an element triggers.';
comment on column xpms.bridge_element_permit.element_id is 'Element.';
comment on column xpms.bridge_element_permit.rule is 'Permit rule.';
create index bridge_element_permit_rule_idx on xpms.bridge_element_permit (rule);

create table xpms.bridge_element_metric (
  element_id xpms.canon_code not null references xpms.elements(element_id),
  domain xpms.canon_code not null,
  item xpms.canon_text not null,
  primary key (element_id, domain, item),
  foreign key (domain, item) references xpms.dim_metric (domain, item)
);
comment on table xpms.bridge_element_metric is 'Metrics that apply to an element.';
comment on column xpms.bridge_element_metric.element_id is 'Element.';
comment on column xpms.bridge_element_metric.domain is 'Metric domain.';
comment on column xpms.bridge_element_metric.item is 'Metric item.';
create index bridge_element_metric_domain_item_idx on xpms.bridge_element_metric (domain, item);

create table xpms.bridge_touchpoint_discipline (
  touchpoint_id xpms.canon_code not null references xpms.dim_touchpoint(touchpoint_id),
  disc_code xpms.canon_code not null references xpms.dim_discipline(disc_code),
  primary key (touchpoint_id, disc_code)
);
comment on table xpms.bridge_touchpoint_discipline is 'Disciplines a touchpoint is delivered through, from the URIDs of the catalog items that realize it.';
comment on column xpms.bridge_touchpoint_discipline.touchpoint_id is 'Touchpoint.';
comment on column xpms.bridge_touchpoint_discipline.disc_code is 'Discipline.';
create index bridge_touchpoint_discipline_disc_code_idx on xpms.bridge_touchpoint_discipline (disc_code);

create table xpms.bridge_discipline_team (
  disc_code xpms.canon_code not null references xpms.dim_discipline(disc_code),
  team_id xpms.canon_code not null references xpms.dim_team(team_id),
  primary key (disc_code, team_id)
);
comment on table xpms.bridge_discipline_team is 'Teams that deliver a discipline.';
comment on column xpms.bridge_discipline_team.disc_code is 'Discipline.';
comment on column xpms.bridge_discipline_team.team_id is 'Team.';
create index bridge_discipline_team_team_id_idx on xpms.bridge_discipline_team (team_id);

create table xpms.jurisdiction_code_set (
  jurisdiction_id xpms.canon_code not null references xpms.jurisdiction(jurisdiction_id) on delete cascade,
  code_set xpms.canon_text not null,
  sort_order integer not null check (sort_order > 0),
  primary key (jurisdiction_id, code_set),
  unique (jurisdiction_id, sort_order)
);
comment on table xpms.jurisdiction_code_set is 'Code sets a jurisdiction adopts, one row each (Bible tab 11, primary_code_sets), in their stated order.';
comment on column xpms.jurisdiction_code_set.jurisdiction_id is 'Jurisdiction adopting the code set.';
comment on column xpms.jurisdiction_code_set.code_set is 'Code set name.';
comment on column xpms.jurisdiction_code_set.sort_order is 'Position in the Bible''s list.';

create table xpms.agency_function (
  function xpms.canon_code not null,
  label xpms.canon_text not null,
  responder boolean not null,
  sort_order integer not null,
  primary key (function),
  unique (label),
  unique (sort_order)
);
comment on table xpms.agency_function is 'Functions an agency serves: emergency responders and regulators (decision D15).';
comment on column xpms.agency_function.function is 'Function token, as protocol steps name it ({fire}, {ems}).';
comment on column xpms.agency_function.label is 'Function label.';
comment on column xpms.agency_function.responder is 'True for emergency responders.';
comment on column xpms.agency_function.sort_order is 'Display order.';

create table xpms.jurisdiction_agency (
  jurisdiction_id xpms.canon_code not null references xpms.jurisdiction(jurisdiction_id),
  function xpms.canon_code not null references xpms.agency_function(function),
  agency xpms.canon_text not null,
  contact xpms.canon_text,
  primary key (jurisdiction_id, function)
);
comment on table xpms.jurisdiction_agency is 'The agency serving each function in a jurisdiction, reached through the project''s venue (decisions D15 and D19).';
comment on column xpms.jurisdiction_agency.jurisdiction_id is 'Jurisdiction served.';
comment on column xpms.jurisdiction_agency.function is 'Function served.';
comment on column xpms.jurisdiction_agency.agency is 'Agency name, as canon names it.';
comment on column xpms.jurisdiction_agency.contact is 'Contact number, where stated.';
create index jurisdiction_agency_function_idx on xpms.jurisdiction_agency (function);

create table xpms.wage_hour_rule (
  jurisdiction_id xpms.canon_code not null references xpms.jurisdiction(jurisdiction_id),
  source xpms.canon_text not null,
  weekly_ot_after_hours numeric check (weekly_ot_after_hours > 0),
  daily_ot_after_hours numeric check (daily_ot_after_hours > 0),
  daily_dt_after_hours numeric,
  min_ot_multiplier numeric check (min_ot_multiplier >= 1),
  min_dt_multiplier numeric,
  primary key (jurisdiction_id),
  check (daily_dt_after_hours is null or daily_ot_after_hours is null or daily_dt_after_hours > daily_ot_after_hours),
  check (min_dt_multiplier is null or min_ot_multiplier is null or min_dt_multiplier >= min_ot_multiplier)
);
comment on table xpms.wage_hour_rule is 'Wage-and-hour minimums a jurisdiction adds to its parent; the strictest value up the chain governs (decision D16).';
comment on column xpms.wage_hour_rule.jurisdiction_id is 'Jurisdiction stating the rule.';
comment on column xpms.wage_hour_rule.source is 'Law the rule comes from.';
comment on column xpms.wage_hour_rule.weekly_ot_after_hours is 'Weekly hours after which overtime applies.';
comment on column xpms.wage_hour_rule.daily_ot_after_hours is 'Daily hours after which overtime applies.';
comment on column xpms.wage_hour_rule.daily_dt_after_hours is 'Daily hours after which double time applies.';
comment on column xpms.wage_hour_rule.min_ot_multiplier is 'Minimum overtime multiplier.';
comment on column xpms.wage_hour_rule.min_dt_multiplier is 'Minimum double-time multiplier.';

create table xpms.organization_type (
  label xpms.canon_text not null,
  primary key (label)
);
comment on table xpms.organization_type is 'Legal forms of an organization (decision D17).';
comment on column xpms.organization_type.label is 'Organization type.';

create table xpms.worker_classification (
  code xpms.canon_code not null check (code ~ '^[A-Z_]+$'),
  label xpms.canon_text not null,
  is_employee boolean not null,
  payment_channel xpms.canon_text not null check (payment_channel in ('Payroll', 'Accounts Payable', 'None')),
  sort_order integer not null,
  primary key (code),
  unique (label),
  unique (sort_order),
  check (not is_employee or payment_channel = 'Payroll')
);
comment on table xpms.worker_classification is 'The legal relationship of a worker, independent of pay computation and schedule (decision D16). Codes are jurisdiction-neutral.';
comment on column xpms.worker_classification.code is 'Classification code.';
comment on column xpms.worker_classification.label is 'Classification label.';
comment on column xpms.worker_classification.is_employee is 'True for an employment relationship.';
comment on column xpms.worker_classification.payment_channel is 'Payroll, Accounts Payable or None.';
comment on column xpms.worker_classification.sort_order is 'Display order.';

create table xpms.classification_document (
  worker_classification xpms.canon_code not null references xpms.worker_classification(code),
  country xpms.canon_code not null references xpms.jurisdiction(jurisdiction_id),
  document xpms.canon_text not null,
  purpose xpms.canon_text not null check (purpose in ('Onboarding', 'Year-End')),
  primary key (worker_classification, country, document)
);
comment on table xpms.classification_document is 'Country documents a classification requires (W-4, I-9, W-2, W-9, 1099-NEC).';
comment on column xpms.classification_document.worker_classification is 'Classification.';
comment on column xpms.classification_document.country is 'Declared country the document belongs to.';
comment on column xpms.classification_document.document is 'Document name.';
comment on column xpms.classification_document.purpose is 'Onboarding or Year-End.';
create index classification_document_country_idx on xpms.classification_document (country);

create table xpms.classification_organization_type (
  worker_classification xpms.canon_code not null references xpms.worker_classification(code),
  organization_type xpms.canon_text not null references xpms.organization_type(label),
  primary key (worker_classification, organization_type)
);
comment on table xpms.classification_organization_type is 'Which organization types may use each worker classification; Volunteer only for Nonprofit and Public Agency (rule XOS-ENG-6).';
comment on column xpms.classification_organization_type.worker_classification is 'Classification.';
comment on column xpms.classification_organization_type.organization_type is 'Organization type allowed to use it.';
create index classification_organization_type_organization_type_idx on xpms.classification_organization_type (organization_type);

create table xpms.pay_basis (
  label xpms.canon_text not null,
  primary key (label)
);
comment on table xpms.pay_basis is 'How pay is computed (decision D16).';
comment on column xpms.pay_basis.label is 'Pay basis.';

create table xpms.arrangement (
  label xpms.canon_text not null,
  primary key (label)
);
comment on table xpms.arrangement is 'The commercial arrangement: a standing retainer or per-engagement work (decision D16).';
comment on column xpms.arrangement.label is 'Arrangement.';

create table xpms.pay_basis_classification (
  pay_basis xpms.canon_text not null references xpms.pay_basis(label),
  worker_classification xpms.canon_code not null references xpms.worker_classification(code),
  primary key (pay_basis, worker_classification)
);
comment on table xpms.pay_basis_classification is 'Lawful or permitted pairs of pay basis and classification. A rate card must match a row.';
comment on column xpms.pay_basis_classification.pay_basis is 'Pay basis.';
comment on column xpms.pay_basis_classification.worker_classification is 'Classification.';
create index pay_basis_classification_worker_classification_idx on xpms.pay_basis_classification (worker_classification);

create table xpms.arrangement_classification (
  arrangement xpms.canon_text not null references xpms.arrangement(label),
  worker_classification xpms.canon_code not null references xpms.worker_classification(code),
  primary key (arrangement, worker_classification)
);
comment on table xpms.arrangement_classification is 'Permitted pairs of arrangement and classification; Retainer is Independent Contractor only.';
comment on column xpms.arrangement_classification.arrangement is 'Arrangement.';
comment on column xpms.arrangement_classification.worker_classification is 'Classification.';
create index arrangement_classification_worker_classification_idx on xpms.arrangement_classification (worker_classification);

create table xpms.overtime_rule (
  rule_id xpms.canon_code not null check (rule_id ~ '^OTR-[0-9]{3}$'),
  name xpms.canon_text not null,
  ot_multiplier numeric not null check (ot_multiplier >= 1),
  dt_multiplier numeric not null,
  primary key (rule_id),
  unique (name),
  unique (ot_multiplier, dt_multiplier),
  check (dt_multiplier >= ot_multiplier)
);
comment on table xpms.overtime_rule is 'Overtime and double-time multipliers, stored once as numbers (decision D14). 1.5x is display formatting.';
comment on column xpms.overtime_rule.rule_id is 'Rule code OTR-nnn.';
comment on column xpms.overtime_rule.name is 'Rule name.';
comment on column xpms.overtime_rule.ot_multiplier is 'Overtime multiplier.';
comment on column xpms.overtime_rule.dt_multiplier is 'Double-time multiplier.';

create table xpms.role_discipline (
  name xpms.canon_text not null,
  primary key (name)
);
comment on table xpms.role_discipline is 'Disciplines of the Roles Library, each stored once (decision D12).';
comment on column xpms.role_discipline.name is 'Discipline label.';

create table xpms.role_rank (
  label xpms.canon_text not null,
  primary key (label)
);
comment on table xpms.role_rank is 'Ranks of the Roles Library, each stored once (decision D12).';
comment on column xpms.role_rank.label is 'Rank label.';

create table xpms.role (
  role_code xpms.canon_code not null check (role_code ~ '^[0-9]000\.[0-9]{2}\.[0-9]{2}$'),
  class_code xpms.canon_code generated always as (left(role_code, 4)) stored not null references xpms.dim_department(dept_code),
  job_title xpms.canon_text not null,
  discipline xpms.canon_text not null references xpms.role_discipline(name),
  rank xpms.canon_text not null references xpms.role_rank(label),
  job_summary xpms.canon_text,
  key_responsibilities xpms.canon_text,
  qualifications xpms.canon_text,
  physical_requirements xpms.canon_text,
  required_certifications xpms.canon_text,
  default_clearance_tier xpms.canon_text,
  default_radio_channel xpms.canon_text,
  flag boolean,
  notes xpms.canon_text,
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (role_code),
  unique (source_row)
);
comment on table xpms.role is 'The Roles Library (decision D12): owns role codes and job titles. Department derives from the code and is not stored.';
comment on column xpms.role.role_code is 'Role code DDDD.DD.DD.';
comment on column xpms.role.class_code is 'Department class, derived from the role code.';
comment on column xpms.role.job_title is 'Job title; the one home of the title.';
comment on column xpms.role.discipline is 'Discipline.';
comment on column xpms.role.rank is 'Rank.';
comment on column xpms.role.job_summary is 'JOB SUMMARY from the Playbook Roles Library sheet.';
comment on column xpms.role.key_responsibilities is 'KEY RESPONSIBILITIES from the Playbook Roles Library sheet.';
comment on column xpms.role.qualifications is 'QUALIFICATIONS from the Playbook Roles Library sheet.';
comment on column xpms.role.physical_requirements is 'PHYSICAL REQUIREMENTS from the Playbook Roles Library sheet.';
comment on column xpms.role.required_certifications is 'REQUIRED CERTIFICATIONS from the Playbook Roles Library sheet.';
comment on column xpms.role.default_clearance_tier is 'DEFAULT CLEARANCE TIER from the Playbook Roles Library sheet.';
comment on column xpms.role.default_radio_channel is 'DEFAULT RADIO CHANNEL from the Playbook Roles Library sheet.';
comment on column xpms.role.flag is 'FLAG from the Playbook Roles Library sheet.';
comment on column xpms.role.notes is 'NOTES from the Playbook Roles Library sheet.';
comment on column xpms.role.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.role.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.role.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.role.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.role.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
create index role_class_code_idx on xpms.role (class_code);
create index role_discipline_idx on xpms.role (discipline);
create index role_rank_idx on xpms.role (rank);

create table xpms.rate_card (
  rate_card_id xpms.canon_code not null check (rate_card_id ~ '^LRC-[0-9]{3}$'),
  role_code xpms.canon_code not null references xpms.role(role_code),
  worker_classification xpms.canon_code not null,
  pay_basis xpms.canon_text not null,
  arrangement xpms.canon_text not null,
  standard_rate_minor bigint check (standard_rate_minor >= 0),
  min_grade_rate_minor bigint check (min_grade_rate_minor >= 0),
  max_grade_rate_minor bigint check (max_grade_rate_minor >= 0),
  per_diem_rate_minor bigint check (per_diem_rate_minor >= 0),
  currency_code xpms.currency_code not null,
  overtime_rule_id xpms.canon_code not null references xpms.overtime_rule(rule_id),
  flag boolean,
  notes xpms.canon_text,
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (rate_card_id),
  unique (role_code, worker_classification, pay_basis, arrangement),
  unique (source_row),
  foreign key (pay_basis, worker_classification) references xpms.pay_basis_classification (pay_basis, worker_classification),
  foreign key (arrangement, worker_classification) references xpms.arrangement_classification (arrangement, worker_classification),
  check (max_grade_rate_minor is null or min_grade_rate_minor is null or max_grade_rate_minor >= min_grade_rate_minor)
);
comment on table xpms.rate_card is 'Labor Rate Cards (decisions D12 to D14 and D16): only the card''s own facts. Title, department, GL account and multipliers are joined or derived.';
comment on column xpms.rate_card.rate_card_id is 'Rate card code LRC-nnn.';
comment on column xpms.rate_card.role_code is 'Role the card prices.';
comment on column xpms.rate_card.worker_classification is 'Classification of the engagement the card prices.';
comment on column xpms.rate_card.pay_basis is 'How pay is computed.';
comment on column xpms.rate_card.arrangement is 'Retainer or per engagement.';
comment on column xpms.rate_card.standard_rate_minor is 'Standard rate in minor units of currency_code; NULL is unpriced.';
comment on column xpms.rate_card.min_grade_rate_minor is 'Lowest grade rate in minor units of currency_code; NULL is unpriced.';
comment on column xpms.rate_card.max_grade_rate_minor is 'Highest grade rate in minor units of currency_code; NULL is unpriced.';
comment on column xpms.rate_card.per_diem_rate_minor is 'Per diem in minor units of currency_code; NULL is unpriced.';
comment on column xpms.rate_card.currency_code is 'ISO 4217 currency of the amounts; the Playbook states US dollars.';
comment on column xpms.rate_card.overtime_rule_id is 'Overtime rule the card follows.';
comment on column xpms.rate_card.flag is 'FLAG from the Playbook Labor Rate Cards sheet.';
comment on column xpms.rate_card.notes is 'NOTES from the Playbook Labor Rate Cards sheet.';
comment on column xpms.rate_card.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.rate_card.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.rate_card.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.rate_card.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.rate_card.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
create index rate_card_overtime_rule_id_idx on xpms.rate_card (overtime_rule_id);
create index rate_card_pay_basis_worker_classification_idx on xpms.rate_card (pay_basis, worker_classification);
create index rate_card_arrangement_worker_classification_idx on xpms.rate_card (arrangement, worker_classification);

create table xpms.emergency_code (
  code xpms.canon_code not null check (code ~ '^CODE_[A-Z]+$'),
  label xpms.canon_text not null,
  emergency xpms.canon_text not null,
  swatch xpms.canon_code not null check (swatch ~ '^ecode-[a-z]+$'),
  sort_order integer not null,
  primary key (code),
  unique (label),
  unique (swatch),
  unique (sort_order)
);
comment on table xpms.emergency_code is 'Emergency codes, global: no organization, project or jurisdiction (decision D15). Numeric sort order.';
comment on column xpms.emergency_code.code is 'Code token, such as CODE_RED.';
comment on column xpms.emergency_code.label is 'Code word, such as Code Red.';
comment on column xpms.emergency_code.emergency is 'The emergency the code announces.';
comment on column xpms.emergency_code.swatch is 'Design token of the swatch (ecode-*).';
comment on column xpms.emergency_code.sort_order is 'Order of first appearance in the Playbook.';

create table xpms.operational_domain (
  domain xpms.canon_text not null,
  sort_order integer not null,
  primary key (domain),
  unique (sort_order)
);
comment on table xpms.operational_domain is 'Operational domains an emergency protocol is written for.';
comment on column xpms.operational_domain.domain is 'Domain name.';
comment on column xpms.operational_domain.sort_order is 'Order of first appearance in the Playbook.';

create table xpms.emergency_protocol (
  record_key xpms.canon_code not null check (record_key ~ '^EMG-[0-9]{3}$'),
  code xpms.canon_code not null references xpms.emergency_code(code),
  domain xpms.canon_text not null references xpms.operational_domain(domain),
  department xpms.canon_text,
  category xpms.canon_text,
  sub_category xpms.canon_text,
  flag boolean,
  notes xpms.canon_text,
  source_row integer,
  source_status xpms.canon_text,
  source_created_by xpms.canon_text,
  source_created_at timestamp,
  source_updated_at timestamp,
  primary key (record_key),
  unique (code, domain),
  unique (source_row)
);
comment on table xpms.emergency_protocol is 'The protocol for one code in one operational domain. Global; agencies are resolved per jurisdiction.';
comment on column xpms.emergency_protocol.record_key is 'Protocol key EMG-nnn.';
comment on column xpms.emergency_protocol.code is 'Emergency code.';
comment on column xpms.emergency_protocol.domain is 'Operational domain.';
comment on column xpms.emergency_protocol.department is 'DEPARTMENT from the Playbook Emergency Codes sheet.';
comment on column xpms.emergency_protocol.category is 'CATEGORY from the Playbook Emergency Codes sheet.';
comment on column xpms.emergency_protocol.sub_category is 'SUB CATEGORY from the Playbook Emergency Codes sheet.';
comment on column xpms.emergency_protocol.flag is 'FLAG from the Playbook Emergency Codes sheet.';
comment on column xpms.emergency_protocol.notes is 'NOTES from the Playbook Emergency Codes sheet.';
comment on column xpms.emergency_protocol.source_row is 'Row of the Playbook sheet that mirrors this canon row; NULL when the Playbook has no such row.';
comment on column xpms.emergency_protocol.source_status is 'STATUS as recorded on the Playbook row (for example Active).';
comment on column xpms.emergency_protocol.source_created_by is 'CREATED BY as recorded on the Playbook row.';
comment on column xpms.emergency_protocol.source_created_at is 'CREATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
comment on column xpms.emergency_protocol.source_updated_at is 'UPDATED AT as recorded on the Playbook row: a wall-clock time; the Playbook records no time zone.';
create index emergency_protocol_domain_idx on xpms.emergency_protocol (domain);

create table xpms.emergency_protocol_step (
  record_key xpms.canon_code not null references xpms.emergency_protocol(record_key) on delete cascade,
  step_no integer not null check (step_no >= 1),
  body xpms.canon_text not null,
  primary key (record_key, step_no)
);
comment on table xpms.emergency_protocol_step is 'Numbered protocol steps. Steps name services ({fire}, {ems}, {lawEnforcement}, {bombSquad}, {federal}), never an agency.';
comment on column xpms.emergency_protocol_step.record_key is 'Protocol.';
comment on column xpms.emergency_protocol_step.step_no is 'Step number.';
comment on column xpms.emergency_protocol_step.body is 'Step text, sentence case.';

create table xpms.version (
  version_code xpms.canon_code not null,
  generation integer not null check (generation > 0),
  bible_generated_at timestamp not null,
  bible_sha256 xpms.canon_code not null,
  item_catalog_sha256 xpms.canon_code not null,
  gl_chart_sha256 xpms.canon_code not null,
  playbook_sha256 xpms.canon_code not null,
  primary key (version_code)
);
comment on table xpms.version is 'Canon version and generation, with the hashes of the files the seed was generated from.';
comment on column xpms.version.version_code is 'Canon version, such as 4.0.';
comment on column xpms.version.generation is 'Import generation; increases when a canon change ships.';
comment on column xpms.version.bible_generated_at is 'generated_at stated in the Bible _generated tab.';
comment on column xpms.version.bible_sha256 is 'SHA-256 of the Bible workbook.';
comment on column xpms.version.item_catalog_sha256 is 'SHA-256 of the Item Catalog CSV.';
comment on column xpms.version.gl_chart_sha256 is 'SHA-256 of the GL chart CSV.';
comment on column xpms.version.playbook_sha256 is 'SHA-256 of the Production Playbook workbook.';

create table xpms.ratification (
  subject xpms.canon_text not null,
  ratifier xpms.canon_text not null,
  ratified_at timestamptz not null,
  note xpms.canon_text,
  primary key (subject)
);
comment on table xpms.ratification is 'Ratification records. The 4.0 grammar is proposed until a named ratifier is recorded here (Section 3.13).';
comment on column xpms.ratification.subject is 'What is ratified, such as the 4.0 grammar.';
comment on column xpms.ratification.ratifier is 'Named human ratifier.';
comment on column xpms.ratification.ratified_at is 'When the ratification was recorded.';
comment on column xpms.ratification.note is 'Ratification note.';

create table xpms.supersession (
  domain xpms.canon_code not null,
  code xpms.canon_code not null,
  successor_code xpms.canon_code not null,
  label xpms.canon_text not null,
  reason xpms.canon_text not null,
  primary key (domain, code),
  check (code <> successor_code)
);
comment on table xpms.supersession is 'Superseded codes and their successors. Supersession is data, so reverting is a data change; the graph stays acyclic.';
comment on column xpms.supersession.domain is 'Code domain, such as phase.';
comment on column xpms.supersession.code is 'Superseded code; historical references keep resolving.';
comment on column xpms.supersession.successor_code is 'Code that supersedes it.';
comment on column xpms.supersession.label is 'Label the superseded code carried.';
comment on column xpms.supersession.reason is 'Why the code was superseded.';

create table xpms.field_provenance (
  element_id xpms.canon_code not null references xpms.elements(element_id),
  field_name xpms.canon_code not null,
  provenance xpms.canon_code not null references xpms.dim_provenance(provenance),
  recorded_at timestamp not null,
  primary key (element_id, field_name)
);
comment on table xpms.field_provenance is 'Provenance of every populated canon field of an element (Section 3.8). A lower rank never overwrites a field written by a higher rank.';
comment on column xpms.field_provenance.element_id is 'Element whose field was written.';
comment on column xpms.field_provenance.field_name is 'Column of xpms.elements that was written.';
comment on column xpms.field_provenance.provenance is 'Provenance of the write.';
comment on column xpms.field_provenance.recorded_at is 'When the write was recorded (the Bible generation time for imported values).';
create index field_provenance_provenance_idx on xpms.field_provenance (provenance);

create table xpms.intake (
  source_file xpms.canon_text not null,
  source_sheet xpms.canon_text not null,
  source_row integer not null,
  source_column xpms.canon_text not null,
  target_table xpms.canon_code not null,
  target_key xpms.canon_text not null,
  target_column xpms.canon_code not null,
  proposed_value xpms.canon_text,
  canon_value xpms.canon_text,
  reason xpms.canon_text not null,
  intake_state xpms.canon_text not null references xpms.dim_state(state),
  primary key (source_file, source_sheet, source_row, source_column)
);
comment on table xpms.intake is 'Staging for proposed canon additions and changes awaiting an owner decision. Neither source silently wins: a value that disagrees with canon or cannot be resolved waits here.';
comment on column xpms.intake.source_file is 'Canon input file the value comes from.';
comment on column xpms.intake.source_sheet is 'Sheet, tab or CSV the value comes from.';
comment on column xpms.intake.source_row is 'Source row number.';
comment on column xpms.intake.source_column is 'Source column header.';
comment on column xpms.intake.target_table is 'xpms table the value would change.';
comment on column xpms.intake.target_key is 'Natural key of the target row.';
comment on column xpms.intake.target_column is 'Column the value would change.';
comment on column xpms.intake.proposed_value is 'Value as the source states it; NULL when the source is blank.';
comment on column xpms.intake.canon_value is 'Value canon currently holds; NULL when canon is silent.';
comment on column xpms.intake.reason is 'Why the value is held for a decision.';
comment on column xpms.intake.intake_state is 'State of the proposal; Proposed until the owner decides.';
create index intake_intake_state_idx on xpms.intake (intake_state);
