-- 0105_xpms_playbook_tables.sql
-- Generated by @xos/canon-import from canon/source. Do not edit by hand: change the canon
-- files or the importer and run `pnpm --filter @xos/canon-import canon:generate`.
-- Playbook registry, Production Template and Standard Library tables (Section 2.1), defined by canon/map/playbook-columns.yaml.

create table xpms.playbook_sheet (
  sheet_name xpms.canon_text not null,
  sheet_key xpms.canon_code not null,
  ordinal integer not null check (ordinal > 0),
  destination xpms.canon_code not null check (destination in ('canon-mirror', 'standard-library', 'production-template', 'template-metadata')),
  entity xpms.canon_text not null,
  header_row integer,
  used_range xpms.canon_code,
  data_row_count integer not null check (data_row_count >= 0),
  checksum_sha256 xpms.canon_code not null,
  primary key (sheet_name),
  unique (sheet_key),
  unique (ordinal)
);
comment on table xpms.playbook_sheet is 'Every sheet of the Production Playbook with its destination and manifest facts (canon/source/PLAYBOOK_MANIFEST.json).';
comment on column xpms.playbook_sheet.sheet_name is 'Sheet name as the workbook spells it.';
comment on column xpms.playbook_sheet.sheet_key is 'snake_case key used in SQL object names.';
comment on column xpms.playbook_sheet.ordinal is 'Position of the sheet in the workbook.';
comment on column xpms.playbook_sheet.destination is 'canon-mirror, standard-library, production-template or template-metadata.';
comment on column xpms.playbook_sheet.entity is 'Target entity: an xpms table or the app table a later wave creates.';
comment on column xpms.playbook_sheet.header_row is 'Header row; NULL for the Cover Page layout.';
comment on column xpms.playbook_sheet.used_range is 'Range of cells holding values.';
comment on column xpms.playbook_sheet.data_row_count is 'Data rows in the source sheet.';
comment on column xpms.playbook_sheet.checksum_sha256 is 'SHA-256 of the normalized source cells; the round trip must reproduce it.';

create table xpms.playbook_column (
  sheet_name xpms.canon_text not null references xpms.playbook_sheet(sheet_name),
  ordinal integer not null check (ordinal > 0),
  letter xpms.canon_code not null,
  header xpms.canon_text,
  column_key xpms.canon_code not null,
  disposition xpms.canon_code not null check (disposition in ('field', 'computed', 'presentation')),
  target xpms.canon_text,
  data_type xpms.canon_code,
  note xpms.canon_text,
  primary key (sheet_name, ordinal),
  unique (sheet_name, column_key)
);
comment on table xpms.playbook_column is 'The Playbook column map (canon/map/playbook-columns.yaml): every column of every sheet with one disposition.';
comment on column xpms.playbook_column.sheet_name is 'Sheet.';
comment on column xpms.playbook_column.ordinal is 'Column position, 1 for A.';
comment on column xpms.playbook_column.letter is 'Column letters.';
comment on column xpms.playbook_column.header is 'Header text; NULL for Cover Page columns, which have no header row.';
comment on column xpms.playbook_column.column_key is 'snake_case key of the column.';
comment on column xpms.playbook_column.disposition is 'field, computed or presentation.';
comment on column xpms.playbook_column.target is 'schema.table.column the column lands in or feeds.';
comment on column xpms.playbook_column.data_type is 'Data type of the target field.';
comment on column xpms.playbook_column.note is 'Transform, source formula or presentation reason.';

create table xpms.production_template (
  template_code xpms.canon_code not null,
  name xpms.canon_text not null,
  source_file xpms.canon_text not null,
  source_sha256 xpms.canon_code not null,
  is_published boolean not null,
  primary key (template_code)
);
comment on table xpms.production_template is 'The XOS 4.0 Production Template. Applying it creates a project with its records. Private to the owner''s org until the owner approves publishing (Section 2.1).';
comment on column xpms.production_template.template_code is 'Template code.';
comment on column xpms.production_template.name is 'Template name.';
comment on column xpms.production_template.source_file is 'Playbook file the template was imported from.';
comment on column xpms.production_template.source_sha256 is 'SHA-256 of that file.';
comment on column xpms.production_template.is_published is 'True once the owner approves publishing to other tenants; false at import.';

create table xpms.production_template_metadata (
  template_code xpms.canon_code not null references xpms.production_template(template_code),
  source_row integer not null check (source_row > 0),
  column_ordinal integer not null check (column_ordinal > 0),
  value_text xpms.canon_text,
  value_kind xpms.canon_code not null,
  formula xpms.canon_text,
  primary key (template_code, source_row, column_ordinal)
);
comment on table xpms.production_template_metadata is 'Cover Page cells: the template''s metadata, at their source row and column. A formula cell keeps its evaluated value beside its formula.';
comment on column xpms.production_template_metadata.template_code is 'Template.';
comment on column xpms.production_template_metadata.source_row is 'Cover Page row.';
comment on column xpms.production_template_metadata.column_ordinal is 'Cover Page column, 1 for A.';
comment on column xpms.production_template_metadata.value_text is 'Value in lossless text form; NULL for a formula that evaluates to nothing.';
comment on column xpms.production_template_metadata.value_kind is 'Kind of the value: string, number, boolean, date, datetime, time or empty.';
comment on column xpms.production_template_metadata.formula is 'Formula source, for a formula cell.';

create table xpms.production_template_rows (
  template_code xpms.canon_code not null references xpms.production_template(template_code),
  sheet_name xpms.canon_text not null references xpms.playbook_sheet(sheet_name),
  source_row integer not null check (source_row > 1),
  primary key (template_code, sheet_name, source_row)
);
comment on table xpms.production_template_rows is 'Every data row of the 27 record-template sheets, keyed by sheet and source row number.';
comment on column xpms.production_template_rows.template_code is 'Template.';
comment on column xpms.production_template_rows.sheet_name is 'Source sheet.';
comment on column xpms.production_template_rows.source_row is 'Row number in the source sheet.';
create index production_template_rows_sheet_name_idx on xpms.production_template_rows (sheet_name);

create table xpms.production_template_values (
  template_code xpms.canon_code not null,
  sheet_name xpms.canon_text not null,
  source_row integer not null,
  column_ordinal integer not null,
  value_text xpms.canon_text not null,
  value_kind xpms.canon_code not null check (value_kind in ('string', 'number', 'boolean', 'date', 'datetime', 'time')),
  primary key (template_code, sheet_name, source_row, column_ordinal),
  foreign key (template_code, sheet_name, source_row) references xpms.production_template_rows (template_code, sheet_name, source_row),
  foreign key (sheet_name, column_ordinal) references xpms.playbook_column (sheet_name, ordinal)
);
comment on table xpms.production_template_values is 'Literal cell values of template rows. Formula columns are not stored; their views compute them (Section 3.15).';
comment on column xpms.production_template_values.template_code is 'Template.';
comment on column xpms.production_template_values.sheet_name is 'Source sheet.';
comment on column xpms.production_template_values.source_row is 'Row number in the source sheet.';
comment on column xpms.production_template_values.column_ordinal is 'Column position, 1 for A.';
comment on column xpms.production_template_values.value_text is 'Value in lossless text form: ISO dates, shortest round-trip numbers, TRUE or FALSE.';
comment on column xpms.production_template_values.value_kind is 'Kind of the source value.';
create index production_template_values_sheet_name_column_ordinal_idx on xpms.production_template_values (sheet_name, column_ordinal);

create table xpms.std_sop (
  source_row integer not null check (source_row > 1),
  sop_id xpms.canon_text not null,
  title xpms.canon_text,
  operational_domain xpms.canon_text,
  revision xpms.canon_text,
  organization xpms.canon_text,
  project xpms.canon_text,
  department xpms.canon_text,
  category xpms.canon_text,
  sub_category xpms.canon_text,
  accountable_role_code xpms.canon_text,
  required_ppe_compliance_tag xpms.canon_text,
  prerequisites_and_hazards xpms.canon_text,
  procedure_step_1 xpms.canon_text,
  procedure_step_2 xpms.canon_text,
  procedure_step_3 xpms.canon_text,
  procedure_step_4 xpms.canon_text,
  reference_doc_id xpms.canon_text,
  status xpms.canon_text,
  flag boolean,
  notes xpms.canon_text,
  created_by xpms.canon_text,
  created_at timestamp,
  updated_at date,
  primary key (sop_id),
  unique (source_row)
);
comment on table xpms.std_sop is 'XOS Standard Library: SOP Library (Playbook, provenance imported). Each new org receives an editable copy at creation.';
comment on column xpms.std_sop.source_row is 'Row of the Playbook SOP Library sheet the entry was imported from; the library''s default order.';
comment on column xpms.std_sop.sop_id is 'SOP ID from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.title is 'TITLE from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.operational_domain is 'OPERATIONAL DOMAIN from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.revision is 'REVISION from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.organization is 'ORGANIZATION from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.project is 'PROJECT from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.department is 'DEPARTMENT from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.category is 'CATEGORY from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.sub_category is 'SUB CATEGORY from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.accountable_role_code is 'ACCOUNTABLE ROLE CODE from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.required_ppe_compliance_tag is 'REQUIRED PPE / COMPLIANCE TAG from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.prerequisites_and_hazards is 'PREREQUISITES & HAZARDS from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.procedure_step_1 is 'PROCEDURE STEP 1 from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.procedure_step_2 is 'PROCEDURE STEP 2 from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.procedure_step_3 is 'PROCEDURE STEP 3 from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.procedure_step_4 is 'PROCEDURE STEP 4 from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.reference_doc_id is 'REFERENCE DOC ID from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.status is 'STATUS from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.flag is 'FLAG from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.notes is 'NOTES from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.created_by is 'CREATED BY from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.created_at is 'CREATED AT from the Playbook SOP Library sheet.';
comment on column xpms.std_sop.updated_at is 'UPDATED AT from the Playbook SOP Library sheet.';

create table xpms.std_vendor_class (
  source_row integer not null check (source_row > 1),
  record_id xpms.canon_text not null,
  department xpms.canon_text,
  category xpms.canon_text,
  sub_category xpms.canon_text,
  class xpms.canon_text,
  description xpms.canon_text,
  clearance_tier xpms.canon_text,
  status xpms.canon_text,
  flag boolean,
  notes xpms.canon_text,
  created_by xpms.canon_text,
  created_at timestamp,
  updated_at timestamp,
  primary key (record_id),
  unique (source_row)
);
comment on table xpms.std_vendor_class is 'XOS Standard Library: Vendor Classes (Playbook, provenance imported). Each new org receives an editable copy at creation.';
comment on column xpms.std_vendor_class.source_row is 'Row of the Playbook Vendor Classes sheet the entry was imported from; the library''s default order.';
comment on column xpms.std_vendor_class.record_id is 'RECORD ID from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.department is 'DEPARTMENT from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.category is 'CATEGORY from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.sub_category is 'SUB CATEGORY from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.class is 'CLASS from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.description is 'DESCRIPTION from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.clearance_tier is 'CLEARANCE TIER from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.status is 'STATUS from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.flag is 'FLAG from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.notes is 'NOTES from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.created_by is 'CREATED BY from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.created_at is 'CREATED AT from the Playbook Vendor Classes sheet.';
comment on column xpms.std_vendor_class.updated_at is 'UPDATED AT from the Playbook Vendor Classes sheet.';

create table xpms.std_vendor_entitlement (
  source_row integer not null check (source_row > 1),
  record_id xpms.canon_text not null,
  vendor_class xpms.canon_text,
  module xpms.canon_text,
  permitted boolean,
  status xpms.canon_text,
  flag boolean,
  notes xpms.canon_text,
  created_by xpms.canon_text,
  created_at timestamp,
  updated_at timestamp,
  primary key (record_id),
  unique (source_row)
);
comment on table xpms.std_vendor_entitlement is 'XOS Standard Library: Vendor Entitlements (Playbook, provenance imported). Each new org receives an editable copy at creation.';
comment on column xpms.std_vendor_entitlement.source_row is 'Row of the Playbook Vendor Entitlements sheet the entry was imported from; the library''s default order.';
comment on column xpms.std_vendor_entitlement.record_id is 'RECORD ID from the Playbook Vendor Entitlements sheet.';
comment on column xpms.std_vendor_entitlement.vendor_class is 'VENDOR CLASS from the Playbook Vendor Entitlements sheet.';
comment on column xpms.std_vendor_entitlement.module is 'MODULE from the Playbook Vendor Entitlements sheet.';
comment on column xpms.std_vendor_entitlement.permitted is 'PERMITTED from the Playbook Vendor Entitlements sheet.';
comment on column xpms.std_vendor_entitlement.status is 'STATUS from the Playbook Vendor Entitlements sheet.';
comment on column xpms.std_vendor_entitlement.flag is 'FLAG from the Playbook Vendor Entitlements sheet.';
comment on column xpms.std_vendor_entitlement.notes is 'NOTES from the Playbook Vendor Entitlements sheet.';
comment on column xpms.std_vendor_entitlement.created_by is 'CREATED BY from the Playbook Vendor Entitlements sheet.';
comment on column xpms.std_vendor_entitlement.created_at is 'CREATED AT from the Playbook Vendor Entitlements sheet.';
comment on column xpms.std_vendor_entitlement.updated_at is 'UPDATED AT from the Playbook Vendor Entitlements sheet.';

create table xpms.std_radio_channel (
  source_row integer not null check (source_row > 1),
  record_id xpms.canon_text not null,
  department xpms.canon_text,
  category xpms.canon_text,
  sub_category xpms.canon_text,
  zone numeric,
  channel numeric,
  assignment xpms.canon_text,
  status xpms.canon_text,
  flag boolean,
  notes xpms.canon_text,
  created_by xpms.canon_text,
  created_at timestamp,
  updated_at timestamp,
  primary key (record_id),
  unique (source_row)
);
comment on table xpms.std_radio_channel is 'XOS Standard Library: Radio Channels (Playbook, provenance imported). Each new org receives an editable copy at creation.';
comment on column xpms.std_radio_channel.source_row is 'Row of the Playbook Radio Channels sheet the entry was imported from; the library''s default order.';
comment on column xpms.std_radio_channel.record_id is 'RECORD ID from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.department is 'DEPARTMENT from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.category is 'CATEGORY from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.sub_category is 'SUB CATEGORY from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.zone is 'ZONE from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.channel is 'CHANNEL from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.assignment is 'ASSIGNMENT from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.status is 'STATUS from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.flag is 'FLAG from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.notes is 'NOTES from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.created_by is 'CREATED BY from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.created_at is 'CREATED AT from the Playbook Radio Channels sheet.';
comment on column xpms.std_radio_channel.updated_at is 'UPDATED AT from the Playbook Radio Channels sheet.';

create table xpms.std_document_library (
  source_row integer not null check (source_row > 1),
  record_id xpms.canon_text not null,
  document_name xpms.canon_text,
  document_type xpms.canon_text,
  reference_id xpms.canon_text,
  organization xpms.canon_text,
  project xpms.canon_text,
  department xpms.canon_text,
  category xpms.canon_text,
  sub_category xpms.canon_text,
  file_format xpms.canon_text,
  file_size xpms.canon_text,
  storage_url xpms.canon_text,
  version xpms.canon_text,
  issue_date date,
  expiration_date date,
  status xpms.canon_text,
  flag boolean,
  notes xpms.canon_text,
  created_by xpms.canon_text,
  created_at timestamp,
  updated_at timestamp,
  primary key (record_id),
  unique (source_row)
);
comment on table xpms.std_document_library is 'XOS Standard Library: Document & Asset Library (Playbook, provenance imported). Each new org receives an editable copy at creation.';
comment on column xpms.std_document_library.source_row is 'Row of the Playbook Document & Asset Library sheet the entry was imported from; the library''s default order.';
comment on column xpms.std_document_library.record_id is 'RECORD ID from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.document_name is 'DOCUMENT NAME from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.document_type is 'DOCUMENT TYPE from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.reference_id is 'REFERENCE ID from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.organization is 'ORGANIZATION from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.project is 'PROJECT from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.department is 'DEPARTMENT from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.category is 'CATEGORY from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.sub_category is 'SUB CATEGORY from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.file_format is 'FILE FORMAT from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.file_size is 'FILE SIZE from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.storage_url is 'STORAGE URL from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.version is 'VERSION from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.issue_date is 'ISSUE DATE from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.expiration_date is 'EXPIRATION DATE from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.status is 'STATUS from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.flag is 'FLAG from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.notes is 'NOTES from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.created_by is 'CREATED BY from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.created_at is 'CREATED AT from the Playbook Document & Asset Library sheet.';
comment on column xpms.std_document_library.updated_at is 'UPDATED AT from the Playbook Document & Asset Library sheet.';

create table xpms.std_verbiage (
  source_row integer not null check (source_row > 1),
  record_id xpms.canon_text not null,
  department xpms.canon_text,
  category xpms.canon_text,
  sub_category xpms.canon_text,
  verbiage xpms.canon_text,
  title xpms.canon_text,
  body xpms.canon_text,
  description xpms.canon_text,
  status xpms.canon_text,
  flag boolean,
  notes xpms.canon_text,
  created_by xpms.canon_text,
  created_at timestamp,
  updated_at timestamp,
  primary key (record_id),
  unique (source_row)
);
comment on table xpms.std_verbiage is 'XOS Standard Library: Verbiage Library (Playbook, provenance imported). Each new org receives an editable copy at creation.';
comment on column xpms.std_verbiage.source_row is 'Row of the Playbook Verbiage Library sheet the entry was imported from; the library''s default order.';
comment on column xpms.std_verbiage.record_id is 'RECORD ID from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.department is 'DEPARTMENT from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.category is 'CATEGORY from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.sub_category is 'SUB CATEGORY from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.verbiage is 'VERBIAGE from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.title is 'TITLE from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.body is 'BODY from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.description is 'DESCRIPTION from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.status is 'STATUS from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.flag is 'FLAG from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.notes is 'NOTES from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.created_by is 'CREATED BY from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.created_at is 'CREATED AT from the Playbook Verbiage Library sheet.';
comment on column xpms.std_verbiage.updated_at is 'UPDATED AT from the Playbook Verbiage Library sheet.';

create table xpms.std_enumeration (
  source_row integer not null check (source_row > 1),
  record_id xpms.canon_text not null,
  department xpms.canon_text,
  category xpms.canon_text,
  sub_category xpms.canon_text,
  enum_domain xpms.canon_text,
  enum_code xpms.canon_text,
  enum_label xpms.canon_text,
  description xpms.canon_text,
  sort_order numeric,
  color_code xpms.canon_text,
  target_entity xpms.canon_text,
  is_default boolean,
  status xpms.canon_text,
  flag boolean,
  notes xpms.canon_text,
  created_by xpms.canon_text,
  created_at timestamp,
  updated_at timestamp,
  primary key (record_id),
  unique (source_row)
);
comment on table xpms.std_enumeration is 'XOS Standard Library: Enumerations (Playbook, provenance imported). Each new org receives an editable copy at creation.';
comment on column xpms.std_enumeration.source_row is 'Row of the Playbook Enumerations sheet the entry was imported from; the library''s default order.';
comment on column xpms.std_enumeration.record_id is 'RECORD ID from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.department is 'DEPARTMENT from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.category is 'CATEGORY from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.sub_category is 'SUB CATEGORY from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.enum_domain is 'ENUM DOMAIN from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.enum_code is 'ENUM CODE from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.enum_label is 'ENUM LABEL from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.description is 'DESCRIPTION from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.sort_order is 'SORT ORDER from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.color_code is 'COLOR CODE from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.target_entity is 'TARGET ENTITY from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.is_default is 'IS DEFAULT from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.status is 'STATUS from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.flag is 'FLAG from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.notes is 'NOTES from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.created_by is 'CREATED BY from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.created_at is 'CREATED AT from the Playbook Enumerations sheet.';
comment on column xpms.std_enumeration.updated_at is 'UPDATED AT from the Playbook Enumerations sheet.';
